### ISSUE TITLE
ArrayIndexOutOfBoundsException caused by incomplete command line options

### ISSUE THREAD

**Issue by ebourg** [antlr/antlr4#1009]
Hi,

Using ANTLR 4.5.1 I noticed that an incomplete command line option triggers an ArrayIndexOutOfBoundsException, for example:

    $ antlr4 -o
    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
            at org.antlr.v4.Tool.handleArgs(Tool.java:241)
            at org.antlr.v4.Tool.<init>(Tool.java:219)
            at org.antlr.v4.Tool.main(Tool.java:188)

    $ antlr4 -encoding
    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
            at org.antlr.v4.Tool.handleArgs(Tool.java:241)
            at org.antlr.v4.Tool.<init>(Tool.java:219)
            at org.antlr.v4.Tool.main(Tool.java:188)

Comparatively, with antlr3 a proper error message is displayed:

    $ antlr3 -o
    missing output directory with -fo/-o option; ignoring

    $ antlr3 -language
    missing language name; ignoring

**Comment by jimidle** [comment]
Probably better to switch to args4j, which handles all this very nicely.

**Comment by sharwell** [comment]
> Probably better to switch to args4j, which handles all this very nicely.

args4j is a relatively large dependency for what amounts to a very small task in ANTLR. I think we should just fix the handling for this case and not bother changing everything else out.

**Comment by parrt** [comment]
just found another semi-related issue https://github.com/antlr/antlr4/issues/1041
