### ISSUE TITLE
Exception while generating lexer grammar

### ISSUE THREAD

**Issue by spquix** [antlr/antlr4#1056]
Antlr tool throws exception while generating lexer grammar.

Reproduced with:

- Antlr plugin for Intellij Idea
- antlr-4.5-complete.jar, Oracle jdk8 Mac OS X
- antlr-4.5.1-comlere.jar, openjdk-7, Ubuntu

Grammar file attached as:

[AT8024Lexer.g4.txt](https://github.com/antlr/antlr4/files/46609/AT8024Lexer.g4.txt)

Exception:

$ antlr4 AT8024Lexer.g4 
Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element out of range.
	at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:370)
	at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:547)
	at org.antlr.v4.codegen.model.SerializedATN.<init>(SerializedATN.java:46)
	at org.antlr.v4.codegen.model.Recognizer.<init>(Recognizer.java:87)
	at org.antlr.v4.codegen.model.Lexer.<init>(Lexer.java:51)
	at org.antlr.v4.codegen.OutputModelController.lexer(OutputModelController.java:176)
	at org.antlr.v4.codegen.OutputModelController.buildLexerOutputModel(OutputModelController.java:129)
	at org.antlr.v4.codegen.CodeGenerator.generateLexer(CodeGenerator.java:142)
	at org.antlr.v4.codegen.CodeGenPipeline.process(CodeGenPipeline.java:73)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:428)
	at org.antlr.v4.Tool.process(Tool.java:386)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:345)
	at org.antlr.v4.Tool.main(Tool.java:192)

**Comment by spquix** [comment]
It seems antlr throws the exception above every time it encounters something like 'type(SKIP)',
For example:

lexer grammar TLexer;

tokens { WORD, SKIP, EOL }

Word:   [!-~]+      -> type(WORD);
Skip:   ' '         -> type(SKIP);
Eol :   [\r\n]+     -> type(EOL);

// Refactor SKIP to SKIP1 and all goes ok.

**Comment by KvanTTT** [comment]
Your issue (and other) is fixed in my [pull request](https://github.com/antlr/antlr4/pull/1014), which still not merged :(

**Comment by KvanTTT** [comment]
@parrt, I guess this issue also can be closed.
