### ISSUE TITLE
testCollectionQueryDuplicateThrowsAssertionException failing

### ISSUE THREAD

**Issue by jimregan** [antlr/antlr4#1111]
getting two different results - with `println` added:
```java
        try {
            JsonNode first = m.readTree(serializer.toJSON());
            JsonNode second = m.readTree(serializer.toJSON());

            System.err.println("first: " + first.toString());
            System.err.println("second: " + second.toString());
            assert first.at("/collection").equals(second.at("/collection"));
```
I'm getting: 

```
Running de.ids_mannheim.korap.query.serialize.AnnisQueryProcessorTest
log4j:WARN No appenders could be found for logger (de.ids_mannheim.korap.query.serialize.AnnisQueryProcessor).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.682 sec
Running de.ids_mannheim.korap.query.serialize.CollectionQueryDuplicateTest
first: {"@context":"http://korap.ids-mannheim.de/ns/koral/0.3/context.jsonld","collection":{"@type":"koral:docGroup","operation":"operation:and","operands":[{"@type":"koral:doc","key":"textClass","value":"politik","match":"match:eq"},{"@type":"koral:doc","key":"corpusID","value":"WPD","match":"match:eq"}]},"query":{"@type":"koral:token","wrap":{"@type":"koral:term","key":"Haus","layer":"lemma","match":"match:eq"}}}
second: {"@context":"http://korap.ids-mannheim.de/ns/koral/0.3/context.jsonld","collection":{"@type":"koral:docGroup","operation":"operation:and","operands":[{"@type":"koral:docGroup","operation":"operation:and","operands":[{"@type":"koral:doc","key":"textClass","value":"politik","match":"match:eq"},{"@type":"koral:doc","key":"corpusID","value":"WPD","match":"match:eq"}]},{"@type":"koral:docGroup","operation":"operation:and","operands":[{"@type":"koral:doc","key":"textClass","value":"politik","match":"match:eq"},{"@type":"koral:doc","key":"corpusID","value":"WPD","match":"match:eq"}]}]},"query":{"@type":"koral:token","wrap":{"@type":"koral:term","key":"Haus","layer":"lemma","match":"match:eq"}}}
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.278 sec <<< FAILURE!
testCollectionQueryDuplicateThrowsAssertionException(de.ids_mannheim.korap.query.serialize.CollectionQueryDuplicateTest)  Time elapsed: 0.278 sec  <<< FAILURE!
java.lang.AssertionError
	at de.ids_mannheim.korap.query.serialize.CollectionQueryDuplicateTest.testCollectionQueryDuplicateThrowsAssertionException(CollectionQueryDuplicateTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by jimregan** [comment]
sorry, wrong window!
