### ISSUE TITLE
Build fails for Tool Tests: unresolved dependency on itself

### ISSUE THREAD

**Issue by gagern** [antlr/antlr4#1128]
I'm trying to build ANTLR on OS X using Oracle JDK 1.8.0_72 and Maven 3.3.3 installed by MacPorts.

Following the [Building ANTLR](https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md) documentation, I got the latest sources (d0fb48c2b89128158950f4b32a61d50d52d981ea in my case), ran `mvn3 compile` and got this error message:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building ANTLR 4 Tool Tests 4.5.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ANTLR 4 ............................................ SUCCESS [  0.449 s]
[INFO] ANTLR 4 Runtime .................................... SUCCESS [  3.365 s]
[INFO] ANTLR 4 Tool ....................................... SUCCESS [  4.715 s]
[INFO] ANTLR 4 Maven plugin ............................... SUCCESS [  1.500 s]
[INFO] ANTLR 4 Runtime Test Generator ..................... SUCCESS [  1.063 s]
[INFO] ANTLR 4 Tool Tests ................................. FAILURE [  0.016 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.299 s
[INFO] Finished at: 2016-03-07T12:24:37+01:00
[INFO] Final Memory: 42M/460M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project antlr4-tool-testsuite:
Could not resolve dependencies for project org.antlr:antlr4-tool-testsuite:jar:4.5.3-SNAPSHOT:
The following artifacts could not be resolved: org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT,
org.antlr:antlr4-runtime-testsuite:jar:tests:4.5.3-SNAPSHOT: Failure to find
org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT in
https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository,
resolution will not be reattempted until the update interval of sonatype-nexus-snapshots
has elapsed or updates are forced -> [Help 1]
```

(Linebreaks added by me).

I'm not fond of Maven, so I have trouble making sense of this. Why would it try to download the very thing it's trying to build? Perhaps this means that building the test suite fails without printing an error? Running Maven with the `-X` switch, I get more verbose output, but nothing I can understand right now.

```
[INFO] ------------------------------------------------------------------------
[INFO] Building ANTLR 4 Tool Tests 4.5.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin version for org.apache.maven.plugins:maven-javadoc-plugin
[DEBUG] Could not find metadata org.apache.maven.plugins:maven-javadoc-plugin/maven-metadata.xml in local (~/.m2/repository)
[DEBUG] Skipped remote request for org.apache.maven.plugins:maven-javadoc-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for org.apache.maven.plugins:maven-javadoc-plugin to 2.10.3 from repository central (https://repo.maven.apache.org/maven2, default, releases)
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       org.antlr:antlr4-tool-testsuite:4.5.3-SNAPSHOT
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [compile, test]
[DEBUG] Repositories (dependencies): [sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, default, snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce (enforce-maven)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <fail default-value="true">${enforcer.fail}</fail>
  <failFast default-value="false">${enforcer.failFast}</failFast>
  <ignoreCache default-value="false">${enforcer.ignoreCache}</ignoreCache>
  <rules>
    <requireMavenVersion>
      <version>(,2.1.0),(2.1.0,2.2.0),(2.2.0,)</version>
      <message>Maven 2.1.0 and 2.2.0 produce incorrect GPG signatures and checksums respectively.</message>
    </requireMavenVersion>
  </rules>
  <skip default-value="false">${enforcer.skip}</skip>
  <project default-value="${project}"/>
  <session default-value="${session}"/>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <buildFilters default-value="${project.build.filters}"/>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <escapeString>${maven.resources.escapeString}</escapeString>
  <escapeWindowsPaths default-value="true">${maven.resources.escapeWindowsPaths}</escapeWindowsPaths>
  <includeEmptyDirs default-value="false">${maven.resources.includeEmptyDirs}</includeEmptyDirs>
  <outputDirectory default-value="${project.build.outputDirectory}"/>
  <overwrite default-value="false">${maven.resources.overwrite}</overwrite>
  <project default-value="${project}"/>
  <resources default-value="${project.resources}"/>
  <session default-value="${session}"/>
  <supportMultiLineFiltering default-value="false">${maven.resources.supportMultiLineFiltering}</supportMultiLineFiltering>
  <useBuildFilters default-value="true"/>
  <useDefaultDelimiters default-value="true"/>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <basedir default-value="${basedir}"/>
  <buildDirectory default-value="${project.build.directory}"/>
  <classpathElements default-value="${project.compileClasspathElements}"/>
  <compileSourceRoots default-value="${project.compileSourceRoots}"/>
  <compilerId default-value="javac">${maven.compiler.compilerId}</compilerId>
  <compilerReuseStrategy default-value="${reuseCreated}">${maven.compiler.compilerReuseStrategy}</compilerReuseStrategy>
  <compilerVersion>${maven.compiler.compilerVersion}</compilerVersion>
  <debug default-value="true">${maven.compiler.debug}</debug>
  <debuglevel>${maven.compiler.debuglevel}</debuglevel>
  <encoding default-value="${project.build.sourceEncoding}">${encoding}</encoding>
  <executable>${maven.compiler.executable}</executable>
  <failOnError default-value="true">${maven.compiler.failOnError}</failOnError>
  <forceJavacCompilerUse default-value="false">${maven.compiler.forceJavacCompilerUse}</forceJavacCompilerUse>
  <fork default-value="false">${maven.compiler.fork}</fork>
  <generatedSourcesDirectory default-value="${project.build.directory}/generated-sources/annotations"/>
  <maxmem>${maven.compiler.maxmem}</maxmem>
  <meminitial>${maven.compiler.meminitial}</meminitial>
  <mojoExecution>${mojoExecution}</mojoExecution>
  <optimize default-value="false">${maven.compiler.optimize}</optimize>
  <outputDirectory default-value="${project.build.outputDirectory}"/>
  <projectArtifact default-value="${project.artifact}"/>
  <showDeprecation default-value="false">${maven.compiler.showDeprecation}</showDeprecation>
  <showWarnings default-value="false">${maven.compiler.showWarnings}</showWarnings>
  <skipMain>${maven.main.skip}</skipMain>
  <skipMultiThreadWarning default-value="false">${maven.compiler.skipMultiThreadWarning}</skipMultiThreadWarning>
  <source default-value="1.5">1.6</source>
  <staleMillis default-value="0">${lastModGranularityMs}</staleMillis>
  <target default-value="1.5">1.6</target>
  <useIncrementalCompilation default-value="true">${maven.compiler.useIncrementalCompilation}</useIncrementalCompilation>
  <verbose default-value="false">${maven.compiler.verbose}</verbose>
  <mavenSession default-value="${session}"/>
  <session default-value="${session}"/>
</configuration>
[DEBUG] =======================================================================
[DEBUG] Could not find metadata org.antlr:antlr4:4.5.3-SNAPSHOT/maven-metadata.xml in local (~/.m2/repository)
[DEBUG] Failure to find org.antlr:antlr4:4.5.3-SNAPSHOT/maven-metadata.xml in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
[DEBUG] Could not find metadata org.antlr:antlr4-runtime-testsuite:4.5.3-SNAPSHOT/maven-metadata.xml in local (~/.m2/repository)
[DEBUG] Failure to find org.antlr:antlr4-runtime-testsuite:4.5.3-SNAPSHOT/maven-metadata.xml in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=24, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=10, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1, ConflictResolver.conflictItemCount=23, DefaultDependencyCollector.collectTime=8, DefaultDependencyCollector.transformTime=2}
[DEBUG] org.antlr:antlr4-tool-testsuite:jar:4.5.3-SNAPSHOT
[DEBUG]    org.antlr:ST4:jar:4.0.8:compile
[DEBUG]       org.antlr:antlr-runtime:jar:3.5.2:compile
[DEBUG]    org.antlr:antlr4-runtime:jar:4.5.3-SNAPSHOT:compile
[DEBUG]    org.antlr:antlr4-runtime-testsuite:jar:4.5.3-SNAPSHOT:compile
[DEBUG]    org.antlr:antlr4:jar:4.5.3-SNAPSHOT:compile
[DEBUG]       org.abego.treelayout:org.abego.treelayout.core:jar:1.0.1:compile
[DEBUG]    org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT:compile
[DEBUG]    org.antlr:antlr4-runtime-testsuite:jar:tests:4.5.3-SNAPSHOT:compile
[DEBUG]    junit:junit:jar:4.11:test
[DEBUG]       org.hamcrest:hamcrest-core:jar:1.3:test
[DEBUG] Could not find metadata org.antlr:antlr4:4.5.3-SNAPSHOT/maven-metadata.xml in local (~/.m2/repository)
[DEBUG] Failure to find org.antlr:antlr4:4.5.3-SNAPSHOT/maven-metadata.xml in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
[DEBUG] Could not find metadata org.antlr:antlr4-runtime-testsuite:4.5.3-SNAPSHOT/maven-metadata.xml in local (~/.m2/repository)
[DEBUG] Failure to find org.antlr:antlr4-runtime-testsuite:4.5.3-SNAPSHOT/maven-metadata.xml in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ANTLR 4 ............................................ SUCCESS [  0.468 s]
[INFO] ANTLR 4 Runtime .................................... SUCCESS [  3.486 s]
[INFO] ANTLR 4 Tool ....................................... SUCCESS [  5.037 s]
[INFO] ANTLR 4 Maven plugin ............................... SUCCESS [  1.445 s]
[INFO] ANTLR 4 Runtime Test Generator ..................... SUCCESS [  1.434 s]
[INFO] ANTLR 4 Tool Tests ................................. FAILURE [  0.025 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.082 s
[INFO] Finished at: 2016-03-07T12:33:05+01:00
[INFO] Final Memory: 42M/511M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project antlr4-tool-testsuite: Could not resolve dependencies for project org.antlr:antlr4-tool-testsuite:jar:4.5.3-SNAPSHOT: The following artifacts could not be resolved: org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT, org.antlr:antlr4-runtime-testsuite:jar:tests:4.5.3-SNAPSHOT: Failure to find org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project antlr4-tool-testsuite: Could not resolve dependencies for project org.antlr:antlr4-tool-testsuite:jar:4.5.3-SNAPSHOT: The following artifacts could not be resolved: org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT, org.antlr:antlr4-runtime-testsuite:jar:tests:4.5.3-SNAPSHOT: Failure to find org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.antlr:antlr4-tool-testsuite:jar:4.5.3-SNAPSHOT: The following artifacts could not be resolved: org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT, org.antlr:antlr4-runtime-testsuite:jar:tests:4.5.3-SNAPSHOT: Failure to find org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT, org.antlr:antlr4-runtime-testsuite:jar:tests:4.5.3-SNAPSHOT: Failure to find org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT, org.antlr:antlr4-runtime-testsuite:jar:tests:4.5.3-SNAPSHOT: Failure to find org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.antlr:antlr4:jar:tests:4.5.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :antlr4-tool-testsuite
```

(I replaced my actual home directory with `~` in this log.)

**Comment by gagern** [comment]
Note: `mvn -DskipTests install` succeeds. Perhaps it's important that each submodule gets installed, not only built?

**Comment by parrt** [comment]
what dir are you in? Should be the root proj dir.

**Comment by gagern** [comment]
It is. I think you should be able to reproduce this if you could clear out your maven cache directory before doing so.

**Comment by parrt** [comment]
I just tried:

```
varmint:master:~/antlr/code/antlr4 $ rm -rf ~/.m2/repository/org/antlr/antlr4
varmint:master:~/antlr/code/antlr4 $ mvn clean test
...
```

Works fine. I killed it after it started running the tests. I use homebrew not macports so maybe that's it? what version of maven?

```
varmint:master:~/antlr/code/antlr4 $ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.7.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.3", arch: "x86_64", family: "mac"
```

**Comment by gagern** [comment]
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.3", arch: "x86_64", family: "mac"
```

I can think of two other possible causes.

1. You did invoke the `test` target, but the docs only mention `compile`. The tests fail for me (see #1156), so I don't know whether the build would succeed after that if the tests would complete successfully. Does a `compile` without `test` work for you?
2. Since the original error message complains about `org.antlr:antlr4-tool-testsuite`, I'd say `rm -rf ~/.m2/repository/org/antlr/antlr4` is one level too specific. Can you clear (or move) the whole `org/antlr` and try again?

**Comment by parrt** [comment]
ok, i got it. i needed to do a deploy of 4.5.4-SNAPSHOT because the tool tests depend on that and it can't seem to find it unless I did deploy. actually I guess install would have worked as well maybe. can you try it now?

**Comment by gagern** [comment]
As I wrote [above](https://github.com/antlr/antlr4/issues/1128#issuecomment-193228521), `mvn install` did work. And I can confirm that `mvn compile` with a newly cleaned repository now works as well. Thanks a lot!

**Comment by ereyes01** [comment]
I hit this error again running `mvn compile` for 4.6 (was building to play with the newly integrated Go target):

```
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/antlr/antlr4-runtime-testsuite/4.6-SNAPSHOT/antlr4-runtime-testsuite-4.6-SNAPSHOT-tests.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/antlr/antlr4/4.6-SNAPSHOT/antlr4-4.6-SNAPSHOT-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ANTLR 4 ........................................... SUCCESS [6.917s]
[INFO] ANTLR 4 Runtime ................................... SUCCESS [13.816s]
[INFO] ANTLR 4 Tool ...................................... SUCCESS [24.804s]
[INFO] ANTLR 4 Maven plugin .............................. SUCCESS [19.518s]
[INFO] ANTLR 4 Runtime Test Annotations .................. SUCCESS [12.135s]
[INFO] ANTLR 4 Runtime Test Processors ................... SUCCESS [0.572s]
[INFO] ANTLR 4 Runtime Tests (2nd generation) ............ SUCCESS [17.992s]
[INFO] ANTLR 4 Tool Tests ................................ FAILURE [1.669s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:06.471s (Wall Clock)
[INFO] Finished at: Fri Nov 18 21:24:21 CST 2016
[INFO] Final Memory: 50M/274M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project antlr4-tool-testsuite: Could not resolve dependencies for project org.antlr:antlr4-tool-testsuite:jar:4.6-SNAPSHOT: The following artifacts could not be resolved: org.antlr:antlr4-runtime-testsuite:jar:tests:4.6-SNAPSHOT, org.antlr:antlr4:jar:tests:4.6-SNAPSHOT: Could not find artifact org.antlr:antlr4-runtime-testsuite:jar:tests:4.6-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :antlr4-tool-testsuite
```

`mvn install` seems to work ok so far, it's running all the tests now...

**Comment by ericvergnaud** [comment]
you first need to run mvn install -DskipTests=true

**Comment by parrt** [comment]
Updated docs to indicate this extra step.
