### ISSUE TITLE
String out of bounds

### ISSUE THREAD

**Issue by arturrataj** [antlr/antlr4#1143]
That's probably due to errors in the parsed file, yet there is no hint which part of the input file is the cause. Perhaps catching such errors by antlr4 and adding such a respective hint, if possible, would help not only in this case.

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at org.antlr.v4.codegen.ActionTranslator.translateAction(ActionTranslator.java:141)
	at org.antlr.v4.codegen.model.InvokeRule.<init>(InvokeRule.java:89)
	at org.antlr.v4.codegen.ParserFactory.ruleRef(ParserFactory.java:129)
	at org.antlr.v4.codegen.OutputModelController.ruleRef(OutputModelController.java:386)
	at org.antlr.v4.codegen.SourceGenTriggers.ruleref(SourceGenTriggers.java:1403)
	at org.antlr.v4.codegen.SourceGenTriggers.atom(SourceGenTriggers.java:1317)
	at org.antlr.v4.codegen.SourceGenTriggers.labeledElement(SourceGenTriggers.java:828)
	at org.antlr.v4.codegen.SourceGenTriggers.element(SourceGenTriggers.java:594)
	at org.antlr.v4.codegen.SourceGenTriggers.alt(SourceGenTriggers.java:427)
	at org.antlr.v4.codegen.SourceGenTriggers.alternative(SourceGenTriggers.java:335)
	at org.antlr.v4.codegen.SourceGenTriggers.block(SourceGenTriggers.java:270)
	at org.antlr.v4.codegen.OutputModelController.buildNormalRuleFunction(OutputModelController.java:306)
	at org.antlr.v4.codegen.OutputModelController.buildRuleFunction(OutputModelController.java:193)
	at org.antlr.v4.codegen.OutputModelController.buildParserOutputModel(OutputModelController.java:119)
	at org.antlr.v4.codegen.CodeGenerator.generateParser(CodeGenerator.java:145)
	at org.antlr.v4.codegen.CodeGenPipeline.process(CodeGenPipeline.java:79)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:429)
	at org.antlr.v4.Tool.process(Tool.java:387)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:346)
	at org.antlr.v4.Tool.main(Tool.java:193)

**Comment by jimidle** [comment]
It looks like this a malformed action, though of course such a situation
should be programmed for or at least the intercepted.

Specifically the code:

    public static List<ActionChunk> translateAction(OutputModelFactory factory,
                                                    RuleFunction rf,
                                                    Token tokenWithinAction,
                                                    ActionAST node)
    {
        String action = tokenWithinAction.getText();
        if ( action.charAt(0)=='{' ) {
            int firstCurly = action.indexOf('{');
            int lastCurly = action.lastIndexOf('}');
            if ( firstCurly>=0 && lastCurly>=0 ) {
                action = action.substring(firstCurly+1, lastCurly); //
trim {...}
            }
        }
        return translateActionChunk(factory, rf, action, node);
    }

Shows that there is an issue looking for the ‘{‘. Perhaps the action string
should be checked for null/empty. Do you have an empty action or something?

Jim
​

**Comment by arturrataj** [comment]
Hi Jim, perhaps it was caused by a rule that did not take any arguments, but its name has still been followed by an empty list of arguments [].

**Comment by arturrataj** [comment]
I was talking about a general mechanism, which in the case of an internal error would report e.g. the last position read, with a clear comment that the position is only "possibly related" to the problem. This might help finding the cause.

**Comment by parrt** [comment]
this is no problem:

```
	    String gS =
	   		"grammar A;\n"+
	   		"a[] : 'a' ;\n" +
	   		"c : a[] c[] ;\n";
	    Grammar g = new Grammar(gS);
```

can you find a grammar that fails?

**Comment by arturrataj** [comment]
Yes Terence. I have just added two such []'s to an otherwise correct grammar and the error could be replicated. I attach the modified grammar.
[vxsp.tar.gz](https://github.com/antlr/antlr4/files/196198/vxsp.tar.gz)

**Comment by parrt** [comment]
dude, could you not send like 10 grammars and expect me to wade through that shit?

**Comment by arturrataj** [comment]
Dear Terence, antlr4 not working because of a probably quite common cause like [] for no arguments was surprising to me, because I guess, that people do such things quite frequently, if not only because Java takes empty parentheses for the same. And thus, I guessed that the error might be caused also by the size of the grammar. Then, you have sent me a short example showing, that [] in fact works in a short grammar.

And thus, I have sent you a long grammar. Checking before the number of instances of []. Let me do it again:

grep -n "\[\]" *
VxspModel.g4:192:common = commonDef[] 'Z' {
VxspModel.g4:229:commonDef[] returns [AsCommon result]

But perhaps, even searching for the []'s is not needed. Parsing the grammar by a parser generator of your choice, with a conditional breakpoint set at a certain call to charAt(), might possibly find out the cause easily.

I suggest ANTLR4, as if I recall it well, it has been advertised as the one working with any shit you throw at it.

And by the way, thanks for a generator which was able to produce a parser for a grammar like that.

**Comment by parrt** [comment]
Perhaps if you sent me just *one* grammar I could find the error. I saw many.

**Comment by arturrataj** [comment]
But it is just a single grammar, even if in several files. The main file is Vxsp.g4:

    grammar Vxsp;
    import Header, VxspModel, Property, Standard, Lists;

and the head is defined in VxspModel.g4:

    compilationUnit[String streamName] returns [ AgentSystem result ]

If you would want my help with it, just tell me.

**Comment by parrt** [comment]
Ah! ok, that's the info I needed. sorry i'm in a bad mood today :(

**Comment by parrt** [comment]
Looks like my guard in b78e0e9c1e3c64798cd23e4c5efcbe94139edef4 fixed this. :) we're good to go!
