### ISSUE TITLE
Help understanding `expected:<[alt 1\n]> but was:<[]>` test failure

### ISSUE THREAD

**Issue by willfaught** [antlr/antlr4#1216]
Any tip for what might be causing the error below? (This is from the Go language target I'm working on.) I haven't debugged it deeply yet, but was hoping this might have a well-known cause.

```
testAmbiguityNoLoop(org.antlr.v4.test.runtime.go.TestFullContextParsing)  Time elapsed: 2.271 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[alt 1
]> but was:<[]>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at org.antlr.v4.test.runtime.go.TestFullContextParsing.testAmbiguityNoLoop(TestFullContextParsing.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

**Comment by willfaught** [comment]
So, for future reference, IIRC, what's happening here is that the wrong rule is being used, so nothing is printed.

**Comment by willfaught** [comment]
Nothing easy to diagnose, unfortunately.

**Comment by parrt** [comment]
That looks like it is incorrectly choosing the second alternative of rule `prog`:

```
grammar T;
prog
@init {this._interp.predictionMode = antlr4.atn.PredictionMode.LL_EXACT_AMBIG_DETECTION;}
	: expr expr {console.log("alt 1");} // <--  should choose this one as it's mentioned first
	| expr
	;
expr: '@'
	| ID '@'
	| ID
	;
ID  : [a-z]+ ;
WS  : [ \r\n\t]+ -> skip ;
```

The input is `a@` which can match either alternative of `prog`. ambiguity resolution should favor the production mentioned first.

**Comment by parrt** [comment]
Closing as all tests pass now.
