### ISSUE TITLE
NullPointerException (offendingToken is null) when Lexer has an error listener

### ISSUE THREAD

**Issue by DavidBiesack** [antlr/antlr4#1224]
I have an ANTLR 4 grammar with an `expression` rule and also a start rule

```
start: expression EOL;
```

if I add a non-null `ANTLRErrorListener` to the Lexer instance

```
 lexer.addErrorListener(l);
```

then try to parse input that has text after the expression such as

```
  1;
```

then I get an `NullPointerException`

on line 560

```
line = offendingToken.getLine();
```

in Parser.java. The member `offendingToken` is `null`. 
The `RecognizerException` is `LexerNoViableAltException(';')`

I'm using ANTLR 4.5.3

```
line 1:1 token recognition error at: ';'
unknown recognition error type: org.antlr.v4.runtime.LexerNoViableAltException
java.lang.NullPointerException
    at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:560)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:155)
    at com.sas.commons.antlr.ErrorHandler.reportError(ErrorHandler.java:126)
    at com.sas.commons.antlr.ErrorHandler$1.syntaxError(ErrorHandler.java:95)
    at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
    at org.antlr.v4.runtime.Lexer.notifyListeners(Lexer.java:386)
    at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:168)
    at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:185)
    at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:168)
    at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:152)
    at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:556)
    at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:412)
    at com.sas.commons.expr.parser.ExprParser.expression(ExprParser.java:252)
    at com.sas.commons.expr.parser.ExprParser.start(ExprParser.java:209)
    at com.sas.commons.expr.parser.ExprParser.parse(ExprParser.java:147)
    at com.sas.commons.expr.parser.test.TestInvalidSyntax.test(TestInvalidSyntax.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by DavidBiesack** [comment]
Note that if I do not add the error listener, but add an error listener to the parser instance, the listener gets no error notification when parsing this. I get a successful parse and no indication that the input is not valid.  That may be a separate issue.

**Comment by jimidle** [comment]
Are you adding a listener designed for parsers to the lever?






On Sun, Jul 3, 2016 at 7:10 AM +0800, "David Biesack" <notifications@github.com> wrote:












Note that if I do not add the error listener, but add an error listener to the parser instance, the listener gets no error notification when parsing this. I get a successful parse and no indication that the input is not valid.  That may be a separate issue.

**Comment by DavidBiesack** [comment]
@jimidle I'm adding a generic `ANTLRErrorListener` which tracks (counts) lexing errors and reports them back to my app as per the Recognizer public method:
```
public void addErrorListener(ANTLRErrorListener listener) {
```

**Comment by parrt** [comment]
Hmm..it looks like your listener is pass a token error to the parser error handler:

```
at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:560)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:155)
    at com.sas.commons.antlr.ErrorHandler.reportError(ErrorHandler.java:126)
    at com.sas.commons.antlr.ErrorHandler$1.syntaxError(ErrorHandler.java:95)
```

either don't do that or maybe change the token you pass to equiv of this (which I put in Lexer#notifyListeners()):

```
		Token errToken = _factory.create(_tokenFactorySourcePair, Token.INVALID_TYPE, text,
		                                 _channel, _tokenStartCharIndex, _input.index(),
		                                 _tokenStartLine, _tokenStartCharPositionInLine);
```
