### ISSUE TITLE
Many tests failing on Windows due to invalid paths

### ISSUE THREAD

**Issue by BurtHarris** [antlr/antlr4#1258]
Updated:   I'm retitling this issue to reflect the fact it was a bug and not just lack of understanding.  See PR #1268 for details on the bug.   

I'm trying to setup so I can contribute to the antlr project by follow the instructions for building antlr4 from sources on a Windows 10 machine.   I initially started with [How-to-build-ANTLR-itself](https://github.com/antlr/antlr4/wiki/How-to-build-ANTLR-itself), but that page seems hopelessly out-of-date, referencing python scripts bild.py etc.   The separate page [building-antlr](https://github.com/antlr/antlr4/blob/d0fb48c2b89128158950f4b32a61d50d52d981ea/doc/building-antlr.md) seem more up-to-date (perhaps the older one should be deleted.)

I think I've installed all the needed pre-requisites (including JDK 1.8.0_101, Maven 3.3.9, node.js v6.3.1 and mono 4.4.42.  None-the-less while compile succeeds, many tests in Java and the mono/c# are failing.  While I'm a long-time C# dev, I'm used to Microsoft's tools, and both mono and Java are a bit unfamiliar to me.   I'm hoping I can get someone to review the test failures and give me a hint how to address them.

**UPDATE: some of the problem may have been due to having Pythong 2.7 rather than 3.5 installed.** *Can someone please help out with a complete list of build/test dependencies?*

Get the source 
----------------

Problems start right away with the git commands as documented:   
```
C:\tmp>git clone git@github.com:antlr/antlr4.git
Cloning into 'antlr4'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm no git wizard, but  `git@github.com:antlr/antlr4.git` looked funny, the following seems to work much better.   Is this equivalent:?
```
C:\tmp>git clone https://github.com/antlr/antlr4.git
Cloning into 'antlr4'...
remote: Counting objects: 61480, done.
remote: Total 61480 (delta 0), reused 0 (delta 0), pack-reused 61480
Receiving objects: 100% (61480/61480), 31.24 MiB | 7.18 MiB/s, done.
Resolving deltas: 100% (32970/32970), done.
Checking connectivity... done.
Checking out files: 100% (1427/1427), done.
```

Compile
---------
This seemed to go well.   I'll attach the log for completeness because I ran into problems later, but I see no warnings or errors:  [compile.txt](https://github.com/antlr/antlr4/files/412402/compile.txt)

Testing tools and targets
----------------------------

This is where I ran into problems.   [install.txt](https://github.com/antlr/antlr4/files/412413/install.txt)

There are a few preliminary warnings I'm unsure how to interpret, but the first outright failures seems to be these:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.antlr.v4.test.runtime.csharp.TestCompositeLexers
dir C:\Users\Burt_\AppData\Local\Temp\TestCompositeLexers-1470877266905
dir C:\Users\Burt_\AppData\Local\Temp\TestCompositeLexers-1470877267468
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.687 sec <<< FAILURE!
testLexerDelegatorInvokesDelegateRule(org.antlr.v4.test.runtime.csharp.TestCompositeLexers)  Time elapsed: 0.565 sec  <<< FAILURE!
java.lang.AssertionError: expected:<S.A
[@0,0:0='a',<3>,1:0]
[@1,1:1='b',<1>,1:1]
[@2,2:2='c',<4>,1:2]
[@3,3:2='<EOF>',<-1>,1:3]
> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.antlr.v4.test.runtime.csharp.BaseTest.assertEquals(BaseTest.java:859)
	at org.antlr.v4.test.runtime.csharp.TestCompositeLexers.testLexerDelegatorInvokesDelegateRule(TestCompositeLexers.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testLexerDelegatorRuleOverridesDelegate(org.antlr.v4.test.runtime.csharp.TestCompositeLexers)  Time elapsed: 0.1 sec  <<< FAILURE!
java.lang.AssertionError: expected:<M.A
[@0,0:1='ab',<1>,1:0]
[@1,2:1='<EOF>',<-1>,1:2]
> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.antlr.v4.test.runtime.csharp.BaseTest.assertEquals(BaseTest.java:859)
	at org.antlr.v4.test.runtime.csharp.TestCompositeLexers.testLexerDelegatorRuleOverridesDelegate(TestCompositeLexers.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```
any guidance would be appreciated...

**Comment by andjo403** [comment]
I got the test to run by installing:
Maven 3.3.9
Microsoft Build Tools 2013 ("C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe")
Mono 4.4.2.11
node.js v4.5.0
python 3.5.2 and 2.7.12
JDK 1.8

MSBuild need to be installed in the path from above.
The path to some of the other tools needs to be added to the maven command e.g.

mvn install -Dantlr-python2-python="C:\Python27\python.exe" -Dantlr-python3-python="C:\Python\Python35-32\python.exe" -Dantlr-javascript-nodejs="C:\Program Files\nodejs\node.exe"
 
I also needed to add a fix see PR #1268 to get the correct paths for windows
hop this is helpful

**Comment by BurtHarris** [comment]
Thank so much!   I just saw your pull request and was just trying to figure out if I need it to make the tests work.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/1268
