### ISSUE TITLE
4.6-SNAPSHOT jar is not working for Swift Target

### ISSUE THREAD

**Issue by hanjoes** [antlr/antlr4#1514]
Getting exception when running:
`java -jar ~/.m2/repository/org/antlr/antlr4/4.6-SNAPSHOT/antlr4-4.6-SNAPSHOT-complete.jar -Dlanguage=Swift Grammar.g4`

```
Exception in thread "main" javax.json.JsonException: Provider org.glassfish.json.JsonProviderImpl not found
        at javax.json.spi.JsonProvider.provider(JsonProvider.java:97)
        at javax.json.Json.createObjectBuilder(Json.java:266)
        at org.antlr.v4.codegen.target.SwiftTarget.serializeTojson(SwiftTarget.java:190)
        at org.antlr.v4.codegen.target.SwiftTarget.getLexerOrParserATNJson(SwiftTarget.java:160)
        at org.antlr.v4.codegen.target.SwiftTarget.genFile(SwiftTarget.java:125)
        at org.antlr.v4.codegen.CodeGenerator.writeRecognizer(CodeGenerator.java:169)
        at org.antlr.v4.codegen.CodeGenPipeline.writeRecognizer(CodeGenPipeline.java:138)
        at org.antlr.v4.codegen.CodeGenPipeline.process(CodeGenPipeline.java:56)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:404)
        at org.antlr.v4.Tool.process(Tool.java:354)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:321)
        at org.antlr.v4.Tool.main(Tool.java:168)
Caused by: java.lang.ClassNotFoundException: org.glassfish.json.JsonProviderImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at javax.json.spi.JsonProvider.provider(JsonProvider.java:94)
        ... 11 more
```

Problem is the dependency in tools only provides API for compilation but no implementation.
```
<dependency>
      <groupId>javax.json</groupId>
      <artifactId>javax.json-api</artifactId>
      <version>1.0</version>
</dependency>
```

By switching to a different JSON library will solve the issue.

**Comment by parrt** [comment]
@hanjoes Which lib should we include? I thought this json lib was working before?

**Comment by hanjoes** [comment]
We could instead use
```
<dependency>
	<groupId>org.glassfish</groupId>
	<artifactId>javax.json</artifactId>
	<version>1.0.4</version>
</dependency>
```
Which contains API and Impl.
During summer it worked but i think @janyou had added the dependency, not sure when it's removed. And the runtime unit tests are working because we have the glassfish json as test dependency. But when you run from command-line and specify language as Swift, the tool will throw the exception above.

**Comment by parrt** [comment]
Ok, i'll add.
