### ISSUE TITLE
crash upon bad grammar

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1556]
Grammar from https://github.com/antlr/intellij-plugin-v4/issues/290 crashes antlr:

```
beast:/tmp $ a4.6 PowerBasic.g4 
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
error(20): PowerBasic.g4:18:14: internal error: Rule perfectSyncCommands undefined 
error(20):  internal error: element list has first|last == null 
Exception in thread "main" java.lang.NullPointerException
	at org.antlr.v4.automata.ParserATNFactory.elemList(ParserATNFactory.java:481)
	at org.antlr.v4.automata.ParserATNFactory.alt(ParserATNFactory.java:450)
	at org.antlr.v4.parse.ATNBuilder.alternative(ATNBuilder.java:557)
	at org.antlr.v4.parse.ATNBuilder.ruleBlock(ATNBuilder.java:291)
	at org.antlr.v4.automata.ParserATNFactory._createATN(ParserATNFactory.java:161)
	at org.antlr.v4.automata.ParserATNFactory.createATN(ParserATNFactory.java:108)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:389)
	at org.antlr.v4.Tool.process(Tool.java:362)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:321)
	at org.antlr.v4.Tool.main(Tool.java:168)
```

**Comment by KvanTTT** [comment]
A minimal grammar for reproduction:
```ANTLR
grammar A;
a:  '1' 'A'..'Z' ;
```

**Comment by parrt** [comment]
Thanks @KvanTTT you are a scholar and a gentleman! :)
