### ISSUE TITLE
BailErrorStrategy in JavaScript

### ISSUE THREAD

**Issue by fdeitelhoff** [antlr/antlr4#1638]
I'm working with ANTLR 4.6 and the JavaScript Target. I'm wondering if a BailErrorStrategy exists in JavaScript, too?

I tried something like this: `parser._errHandler = new antlr4.error.BailErrorStrategy();` but I get errors when I'm trying to parse input:

```
Error: ParseCancellationException is not a constructor

TypeError: ParseCancellationException is not a constructor
    at BailErrorStrategy.recover (E:\Masterthesis\Simplex-Electron\node_modules\antlr4\error\ErrorStrategy.js:743:11)
    at SimplexParser.expression (E:\Masterthesis\Simplex-Electron\src\Model\Simplex-Lang\SimplexParser.js:2926:27)
    at SimplexParser.expression (E:\Masterthesis\Simplex-Electron\src\Model\Simplex-Lang\SimplexParser.js:2840:46)
    at SimplexParser.assignmentStatement (E:\Masterthesis\Simplex-Electron\src\Model\Simplex-Lang\SimplexParser.js:1597:33)
    at SimplexParser.statement (E:\Masterthesis\Simplex-Electron\src\Model\Simplex-Lang\SimplexParser.js:1215:34)
    at SimplexParser.typeless (E:\Masterthesis\Simplex-Electron\src\Model\Simplex-Lang\SimplexParser.js:619:18)
    at SimplexParser.simplex (E:\Masterthesis\Simplex-Electron\src\Model\Simplex-Lang\SimplexParser.js:343:18)
    at SimplexCompiler.parse (E:\Masterthesis\Simplex-Electron\src\Model\Compiler\SLX\SimplexCompiler.js:42:29)
```

Am I missing something? Is the BailErrorStrategy not available in JavaScript?

**Comment by parrt** [comment]
Fixed by #1639
