### ISSUE TITLE
NullPointerException when TestRig run with no command line parameters

### ISSUE THREAD

**Issue by rhouse** [antlr/antlr4#174]
When I invoke TestRig with no command line parameters, I get the expected help text, but then a NullPointerException is thrown as shown here:

roger@roger-euler:~/OpenSourceCode/antlr/learn$ grun
java org.antlr.v4.runtime.misc.TestRig GrammarName startRuleName
  [-tokens] [-tree] [-gui] [-ps file.ps] [-encoding encodingname]
  [-trace] [-diagnostics] [-SLL]
  [input-filename(s)]
Use startRuleName='tokens' if GrammarName is a lexer grammar.
Omitting input-filename makes rig read from stdin.
Exception in thread "main" java.lang.NullPointerException
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:287)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at org.antlr.v4.runtime.misc.TestRig.process(TestRig.java:157)
    at org.antlr.v4.runtime.misc.TestRig.main(TestRig.java:142)

Here is the definition of grun in my .bashrc file:

alias grun='java org.antlr.v4.runtime.misc.TestRig'

**Comment by vernetto** [comment]
I am having the same issue with antlr R4 and jdk1.8.0_141 on Centos7

java -cp /home/centos/antlr/antlr-4.0-complete.jar:. org.antlr.v4.runtime.misc.TestRig

java.lang.NullPointerException
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:311)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.antlr.v4.runtime.misc.TestRig.process(TestRig.java:157)
	at org.antlr.v4.runtime.misc.TestRig.main(TestRig.java:142)
