### ISSUE TITLE
Null ptr exception in SqlBase.g4

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#1815]
[SqlBase.g4](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4) gives

```bash
$ a4.7 SqlBase.g4 
warning(156): SqlBase.g4:951:7: invalid escape sequence
warning(156): SqlBase.g4:951:16: invalid escape sequence
warning(156): SqlBase.g4:951:41: invalid escape sequence
error(144): SqlBase.g4:951:15: multi-character literals are not allowed in lexer sets: '
Exception in thread "main" java.lang.NullPointerException
	at org.antlr.v4.automata.ParserATNFactory.elemList(ParserATNFactory.java:469)
	at org.antlr.v4.automata.ParserATNFactory.alt(ParserATNFactory.java:455)
	at org.antlr.v4.parse.ATNBuilder.alternative(ATNBuilder.java:559)
	at org.antlr.v4.parse.ATNBuilder.ruleBlock(ATNBuilder.java:293)
	at org.antlr.v4.automata.ParserATNFactory._createATN(ParserATNFactory.java:161)
	at org.antlr.v4.automata.LexerATNFactory.createATN(LexerATNFactory.java:120)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:389)
	at org.antlr.v4.Tool.process(Tool.java:354)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:321)
	at org.antlr.v4.Tool.main(Tool.java:168)
```

The `'\"` give that "multi-character literals are not ..." error. Should be better as that will be common.

**Comment by parrt** [comment]
Crap. Got too focused on error messages and antlr tests. forgot to test on SqlBase.g4! Now I get:

```
warning(156): SqlBase.g4:951:7: invalid escape sequence \"
warning(156): SqlBase.g4:951:16: invalid escape sequence \"
warning(156): SqlBase.g4:951:41: invalid escape sequence \"
error(144): SqlBase.g4:951:15: multi-character literals are not allowed in lexer sets: '\
Exception in thread "main" java.lang.NullPointerException
	at org.antlr.v4.automata.ParserATNFactory.elemList(ParserATNFactory.java:469)
...
```
