### ISSUE TITLE
Unable to use square brackets as template delimiters

### ISSUE THREAD

**Issue by Jericho** [antlr/antlr4#1924]
Using StringTemplate4 nuget package version 4.0.8 in Visual Studio 2015. 

The following C# code:
```
var st = new Template("Dear [firstname]", '[', ']');
st.Add("firstname", "Bob");
var result = st.Render();
```
Yields the following exception: `Exception of type 'Antlr4.StringTemplate.Compiler.TemplateException' was thrown.` with the following stack trace:

```
at Antlr4.StringTemplate.Compiler.TemplateCompiler.ReportMessageAndThrowTemplateException(ITokenStream tokens, IToken templateToken, Parser parser, RecognitionException re)
at Antlr4.StringTemplate.Compiler.TemplateCompiler.Compile(String srcName, String name, List`1 args, String template, IToken templateToken)
at Antlr4.StringTemplate.Template..ctor(TemplateGroup group, String template)
```

I had a discussion with Sam Harwell in the `antlrcs` gitter room and he pointed out that the issue is with the closing square bracket.

**Comment by ericvergnaud** [comment]
Ok so that's NOT an antlr issue.
Can you move this out of the antlr space into the string template space?

Envoyé de mon iPhone

**Comment by Jericho** [comment]
Sorry about that. Issue [moved to the StringTemplate4 repo](https://github.com/antlr/stringtemplate4/issues/183)
