### ISSUE TITLE
Stackoverflow after upgrading from 4.6 to 4.7

### ISSUE THREAD

**Issue by nielsbasjes** [antlr/antlr4#1943]
While trying to update the Antlr version in my project (https://github.com/nielsbasjes/yauaa) from version 4.6 to 4.7 I ran into an unexpected Stackoverflow.
I have managed to reduce the problem reproduction to the following very small grammar.
( Full code available via https://github.com/nielsbasjes/Antlr47Stackoverflow )

Experiment.g4

```
grammar Experiment;

// ==================
// Lexer

SPACE
    : (' '|'\t'|'+') -> skip
    ;

fragment EMailWord
    : [a-zA-Z0-9-+_]+
    ;

fragment EMailTLD
    :  [a-zA-Z]+  // No tld has numbers in it
    ;

EMAIL
    : EMailWord ('.' EMailWord )* '@' EMailWord ('.' EMailWord )* '.' EMailTLD
    ;

VERSION
    : [0-9]+ ('.' [0-9]+)*
    ;

WORD
    : [a-zA-Z]+
    ;

// ==================
// Parser

start
    : WORD
    ;

```

and the a simple Java unit test to do a parse action against this

```
package nl.basjes;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CodePointCharStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.junit.Test;

public class TestAntlr47 {

    @Test
    public void simpleTest(){
        String something = "Something";
        CodePointCharStream input = CharStreams.fromString(something);
        ExperimentLexer lexer = new ExperimentLexer(input);

        CommonTokenStream tokens = new CommonTokenStream(lexer);
        ExperimentParser parser = new ExperimentParser(tokens);

        parser.start();
    }

}
```

The top of the stack trace looks like this:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running nl.basjes.TestAntlr47
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.087 sec <<< FAILURE!
simpleTest(nl.basjes.TestAntlr47)  Time elapsed: 0.063 sec  <<< ERROR!
java.lang.StackOverflowError
	at org.antlr.v4.runtime.atn.LexerATNSimulator.getEpsilonTarget(LexerATNSimulator.java:475)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:456)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
```

**Comment by nielsbasjes** [comment]
I just found that this must be a lexer problem because when I reduce the java code to this the problem also occurs.

        String something = "Something";
        CodePointCharStream input = CharStreams.fromString(something);
        ExperimentLexer lexer = new ExperimentLexer(input);
        lexer.getAllTokens();

**Comment by KvanTTT** [comment]
Your lexer rule is incorrect. It's possible to use a hyphen only for ranges (`[a-z]` or on the edge of char set (`[+-]`, `[-+]`). In other cases you have to escape hyphen:
```
WORD   : [a-zA-Z0-9\-+]+ ;
```

Meanwhile, the issue is correct: StackOverflowError is unexpected.

**Comment by nielsbasjes** [comment]
Yes! Thank you for pointing out my mistake.

**Comment by KvanTTT** [comment]
Please, do not close this issue. This is a real bug.

**Comment by nielsbasjes** [comment]
Don't worry. I know. 
As far as my knowledge of Antlr itself goes I would expect two fixes: The Grammar parser should throw an error in this case and the infinite recursion should be fixed.

**Comment by ericvergnaud** [comment]
Probably just one bug i.e. prevent generation of lexers with illegal intervals

**Comment by ice1000** [comment]
I have encountered something similar, but I've managed to fix it by the following code:

![image](https://user-images.githubusercontent.com/16398479/142709067-2ff9e4fb-02e7-467b-b2d8-c36a1218c7fe.png)

**Comment by KvanTTT** [comment]
Hi. It seems your problem does not relate to this issue.

**Comment by KvanTTT** [comment]
@ice1000 seems like closure on `EOF` should be disallowed. I fixed it in a recent merge request.

**Comment by ice1000** [comment]
> Hi. It seems your problem does not relate to this issue.

Lmao

**Comment by ice1000** [comment]
> @ice1000 seems like closure on `EOF` should be disallowed. I fixed it in a recent merge request.

Great job!
