### ISSUE TITLE
NullPointerException in LexerGrammar.createLexerInterpreter() on invalid grammar

### ISSUE THREAD

**Issue by oranoran** [antlr/antlr4#2153]
When creating a grammar that is missing a single quote to close a token, not getting a proper exception.
Instead, getting a NullPointerException when trying to actually use the lexer.

Sample test code (JUnit):
```java
    @Test
    public void bugReproduction() throws Exception {
        String grammarWithMissingQuote = "grammar test;\nr0: r1+;\nr1: 'ABC' | 'ABCDE;";
        LexerGrammar lg = new LexerGrammar(grammarWithMissingQuote);
        CharStream inputStream = CharStreams.fromReader(new StringReader("AB"));
        lg.createLexerInterpreter(inputStream);
    }
```
This throws NullPointerException straight out of Grammar.createLexerInterpreter at line 1299, due to ```implicitLexer``` not being initialized. I would expect the LexerGrammar constructor to throw instead of succeeding but not really initializing.

**Comment by Willam2004** [comment]
i use the code: 
```
LexerGrammar lg = new LexerGrammar(
            "lexer grammar L;\\n" +
                "A : 'a' ;\\n" +
                "B : 'b' ;\\n" +
                "C : 'c' ;\\n");
        Grammar g = new Grammar(
            "parser grammar T;\\n" +
                "s : (A|B)* C ;\\n",
            lg);
        String input = "a * c";
        LexerInterpreter lexEngine =
            lg.createLexerInterpreter(CharStreams.fromString(input));
        CommonTokenStream tokens = new CommonTokenStream(lexEngine);
        ParserInterpreter parser = g.createParserInterpreter(tokens);
        ParseTree t = parser.parse(g.rules.get("s").index);
        assertNull(t.toStringTree(parser));
```
getting a NullPointerException:

```
java.lang.NullPointerException
	at org.antlr.v4.runtime.atn.ATNSerializer.<init>(ATNSerializer.java:34)
	at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
	at org.antlr.v4.runtime.atn.ATNSerializer.getSerializedAsChars(ATNSerializer.java:605)
	at org.antlr.v4.tool.Grammar.createLexerInterpreter(Grammar.java:1313)
	at com.aliyun.fastmodel.parser.custom.DynamicParserTest.testDynamic2(DynamicParserTest.java:71)
```
