### ISSUE TITLE
null referenece in java but not python?

### ISSUE THREAD

**Issue by Braza** [antlr/antlr4#2195]
Hi! I'm building a [SugarCube ](https://bitbucket.org/tmedwards/sugarcube) parser and got it partially working. While building python targets I got no generation problems but additiveExpr is not executed, so I decided to fall back to grun for visualization, but it requires java classes. Generation of java parser failed.

> braza@braza-virtual-machine ~/Sources/telega_dusk $ antlr4 SugarCubeLexer.g4 
braza@braza-virtual-machine ~/Sources/telega_dusk $ antlr4 SugarCubeParser.g4
Exception in thread "main" java.lang.NullPointerException
	at org.antlr.v4.analysis.LeftRecursiveRuleAnalyzer.getArtificialOpPrecRule(LeftRecursiveRuleAnalyzer.java:211)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRule(LeftRecursiveRuleTransformer.java:116)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRules(LeftRecursiveRuleTransformer.java:71)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:71)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:382)
	at org.antlr.v4.Tool.process(Tool.java:369)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:328)
	at org.antlr.v4.Tool.main(Tool.java:172)

SugarCubeLexer.g4
```
lexer grammar SugarCubeLexer;

TEXT
 : ( ~'<' | '<' ~'<' )+
 ;

OPENMACRO: '<<' -> pushMode(InTag);

mode InTag;

    CLOSEMACRO : '>>' -> popMode;
    VAR : '$';
    OR : '||';
    AND : '&&';
    EQ : '==' | 'eq' | 'is';
    NEQ : '!=' | 'neq';
    GT : '>' | 'gt';
    LT : '<' | 'lt';
    GTEQ : '>=' | 'ge';
    LTEQ : '<='| 'le';
    PLUS : '+';
    MINUS : '-';
    MULT : '*';
    DIV : '/';
    MOD : '%';
    POW : '^';
    NOT : '!';

    SCOL : ';';
    ASSIGN : '=';
    OPAR : '(';
    CPAR : ')';
    OBRACE : '{';
    CBRACE : '}';

    TRUE : 'true';
    FALSE : 'false';
    NIL : 'nil';
    IF : 'if';
    ELSEIF : 'elseif';
    FI : '/if';
    ELSE : 'else';
    //WHILE : 'while';
    //LOG : 'log';
    SET : 'set';

    ID
     : '$'[a-zA-Z_] [a-zA-Z_0-9]*
     ;

    INT
     : [0-9]+
     ;

    FLOAT
     : [0-9]+ '.' [0-9]*
     | '.' [0-9]+
     ;

    STRING
     : '"' (~["\r\n] | '""')* '"'
     ;

    SPACE
     : [ \t\r\n] -> skip
     ;

    OTHER
     : .
     ;
```

SugarCubeParser.g4
```
parser grammar SugarCubeParser;

options { tokenVocab=SugarCubeLexer; language=Python;}

parse
 : block EOF
 ;

block
 : statement*
 ;

statement
 : assignment
 | if_stat
 | text
 | log
 ;

assignment
 : OPENMACRO SET ID ASSIGN expr CLOSEMACRO
 ;

if_stat
 : '<<' IF condition '>>' block ('<<' ELSEIF condition '>>' block)* ('<<' ELSE '>>' block)? '<<' FI '>>'
 ;

condition
 : expr #stat_block
 ;

expr
 : MINUS expr                           #unaryMinusExpr
 | NOT expr                             #notExpr
 | expr op=(MULT | DIV | MOD) expr      #multiplicationExpr
 | expr op=(PLUS | MINUS) expr          #additiveExpr
 | expr op=(LTEQ | GTEQ | LT | GT) expr #relationalExpr
 | expr op=(EQ | NEQ) expr              #equalityExpr
 | expr AND expr                        #andExpr
 | expr OR expr                         #orExpr
 | atom                                 #atomExpr
// expr POW<assoc=right> expr           #powExpr
 ;

atom
 : OPAR expr CPAR #parExpr
 | (INT | FLOAT)  #numberAtom
 | (TRUE | FALSE) #booleanAtom
 | ID             #idAtom
 | STRING         #stringAtom
 | NIL            #nilAtom
 ;

text
 : TEXT
 ;

log
 : OTHER
 ;
```

I noticed nulls in SugarCubeLexer.interp
```
token literal names:
null
null
'<<'
'>>'
'$'
'||'
'&&'
null
null
null
null
null
null
'+'
'-'
'*'
'/'
'%'
'^'
'!'
';'
'='
'('
')'
'{'
'}'
'true'
'false'
'nil'
'if'
'elseif'
'/if'
'else'
'set'
null
null
null
null
null
null

token symbolic names:
...
```

**Comment by Braza** [comment]
Thanks @ericvergnaud! I've missed that param, my bad...
