### ISSUE TITLE
NullPointerException in ATNSerializer

### ISSUE THREAD

**Issue by jvalkeal** [antlr/antlr4#2243]
In below sample `grammar2` throws NPE while `grammar1` doesn't. NPE happens with antlr 4.7.1 but not with 4.7. Something to do with missing `WS`.

```
@Test
public void testNpe() throws Exception {
	String grammar1 = "grammar Hello;\n"
		+ "r  : 'hello' ID ;\n"
		+ "ID : [a-z]+ ;\n"
		+ "WS : [ \\t\\r\\n]+ -> skip\n";

	String grammar2 = "grammar Hello;\n"
		+ "r  : 'hello' ID ;\n"
		+ "ID : [a-z]+ ;\n";

	new LexerGrammar(grammar1);
	new LexerGrammar(grammar2);
}
```

```
java.lang.NullPointerException
	at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:150)
	at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
	at org.antlr.v4.Tool.generateInterpreterData(Tool.java:745)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
	at org.antlr.v4.Tool.process(Tool.java:369)
	at org.antlr.v4.tool.Grammar.<init>(Grammar.java:359)
	at org.antlr.v4.tool.Grammar.<init>(Grammar.java:309)
	at org.antlr.v4.tool.Grammar.<init>(Grammar.java:284)
	at org.antlr.v4.tool.LexerGrammar.<init>(LexerGrammar.java:29)
```

Did a quick debugging and `atn.ruleToTokenType` seems to be null. Also noticed that with `grammar1` it never gets into this line. With `grammar2` this field is not initialised in `LexerATNFactory`.
```
if (atn.grammarType == ATNType.LEXER) {
	if (atn.ruleToTokenType[r] == Token.EOF) {
```

**Comment by HSorensen** [comment]
Your grammar is not a LexerGrammar, but a combined Grammar.
Try:
```java
	new Grammar(grammar1);
	new Grammar(grammar2);
```
The LexerGrammar should throw proper exception iff the grammar is not a Lexer grammar.

**Comment by KvanTTT** [comment]
It is not reproducible on the latest version (4.9.3). Could you please check if it works for you? If so please close the issue.

**Comment by KvanTTT** [comment]
@parrt please close, it's not repoducable for me.
