### ISSUE TITLE
Error: "getInvokingContext is not defined" for JavaScript target

### ISSUE THREAD

**Issue by YuhangGe** [antlr/antlr4#2306]
g4 file:

````g4
// filename: Expr.g4
grammar Expr;

prog locals[k = 0]: line+;

line: ID{console.log($prog::k++)} NL;

ID: [a-zA-Z]+;
NL: '\r'? '\n';
WS: [ \t]+ -> skip;
````

main js code:

````js
// filename: index.js
const antlr4 = require('antlr4');
const fs = require('fs');
const { ExprLexer } = require('./ExprLexer');
const { ExprParser } = require('./ExprParser');
const input = fs.readFileSync('./input.txt', 'utf-8');
const lexer = new ExprLexer(new antlr4.InputStream(input));
const tokens = new antlr4.CommonTokenStream(lexer);
const parser = new ExprParser(tokens);
const tree = parser.prog();
````

test input (input.txt) :

````txt
a
b
c

````

running output:

````
ReferenceError: getInvokingContext is not defined
    at ExprParser.line (/Users/xxxx/test/ExprParser.js:200:17)
    at ExprParser.prog (/Users/xxxx/test/parser/ExprParser.js:124:18)
    at Object.<anonymous> (/Users/xxxx/test/index.js:12:21)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    ...
````

**Comment by bathaeian** [comment]
Hi, I have this problem that you mentioned in this post. 
How can I fix it?

**Comment by ericvergnaud** [comment]
probably unrelated, but your grammar is missing an EOF.
suggest you get support from the google discussion group.

**Comment by bathaeian** [comment]
I found the problem.
I believe it's a bug in antlr.
the keyword of "this" should be added to the beginning of call of getInvokingContext

**Comment by ericvergnaud** [comment]
Hi,

I don’t have much time to look into this right now.

would you be able to test the following in the tool jar:
 - locate the resource org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
 - lines 595 and 596, prepend ’this.’ to getInvokingContext()

If that works out, you’d have an immediate fix, and more time to add the proposed fix and corresponding  test in our test suite.

Eric
