### ISSUE TITLE
'antlr4.tree' has no attribute 'getRuleContext'

### ISSUE THREAD

**Issue by xxllp** [antlr/antlr4#2509]
python3 +antlr4

Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 27, in main
    walker.walk(printer, tree)
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 149, in walk
    self.enterRule(listener, t)
  File "/home/mlp/python/anaconda3/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 161, in enterRule
    ctx = r.getRuleContext()
AttributeError: module 'antlr4.tree' has no attribute 'getRuleContext'

**Comment by ericvergnaud** [comment]
Hi,
not sure what you're doing wrong. getRuleContext is defined.
Please close this and get support from the google discussion group.
