### ISSUE TITLE
JS -> strange parser error: d.reportAttemptingFullContext is not a function

### ISSUE THREAD

**Issue by dhowe** [antlr/antlr4#2623]
Seems this occurs when there is a parser ambiguity, however instead of giving a useful message (the various options, for example), the error below is thrown. I believe it originates at [line 698 of ParserATNSimulator.js](https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js#L698)

  ```
   TypeError: d.reportAttemptingFullContext is not a function
      at /Users/me/git/rita-script/node_modules/antlr4/error/ErrorListener.js:77:37
      at Array.map (<anonymous>)
      at ProxyErrorListener.reportAttemptingFullContext (node_modules/antlr4/error/ErrorListener.js:77:17)
      at ParserATNSimulator.reportAttemptingFullContext (node_modules/antlr4/atn/ParserATNSimulator.js:1700:48)
      at ParserATNSimulator.execATN (node_modules/antlr4/atn/ParserATNSimulator.js:469:18)
      at ParserATNSimulator.adaptivePredict (node_modules/antlr4/atn/ParserATNSimulator.js:361:24)
      at RiScriptParser.expr (lib/RiScriptParser.js:895:33)
      at RiScriptParser.assign (lib/RiScriptParser.js:714:14)
      at RiScriptParser.expr (lib/RiScriptParser.js:874:18)
      at RiScriptParser.script (lib/RiScriptParser.js:203:18)
      at LexParser.parse (src/parser.js:66:26)
      at LexParser.lexParse (src/parser.js:80:17)
      at LexParser.lexParseVisit (src/parser.js:88:21)
      at Context.<anonymous> (tests/script-tests.js:199:21)
```

**Comment by ericvergnaud** [comment]
Looks like your custom error handler does not inherit from the standard one?

**Comment by dhowe** [comment]
I believe it subclasses ParseCancellationException([here](https://github.com/dhowe/rita2/blob/master/src/errors.js)), though I'm sure there's a better way to do it

**Comment by ericvergnaud** [comment]
But not ErrorListener ?

**Comment by dhowe** [comment]
Apparently not (I think that code was borrowed from a post online). Can you point me toward a correctly implement error-handler in js that throws parse-exceptions?

**Comment by ericvergnaud** [comment]
Check ConsoleErrorListener in error/ErrorListener.js

**Comment by dhavalsalwala** [comment]
This needs to be fixed. Getting the same weird error when there is a parser ambiguity.

**Comment by ericvergnaud** [comment]
Hi, there's nothing to fix. Your error listener needs to properly inherit from ErrorListener, which implements reportAttemptingFullContext
