### ISSUE TITLE
When I use -atn param, an java.lang.IllegalArgumentException occur here.

### ISSUE THREAD

**Issue by hagen666** [antlr/antlr4#2659]
Code line : https://github.com/antlr/antlr4/blob/7982187134a6776d13cf8b1f9725f137d08adaec/tool/src/org/antlr/v4/tool/DOTGenerator.java#L262

Stacktrace:
```
Exception in thread "main" java.lang.IllegalArgumentException
        at java.lang.AbstractStringBuilder.appendCodePoint(AbstractStringBuilder.java:800)
        at java.lang.StringBuilder.appendCodePoint(StringBuilder.java:235)
        at org.antlr.v4.tool.DOTGenerator.getDOT(DOTGenerator.java:262)
        at org.antlr.v4.tool.DOTGenerator.getDOT(DOTGenerator.java:174)
        at org.antlr.v4.Tool.generateATNs(Tool.java:693)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:398)
        at org.antlr.v4.Tool.process(Tool.java:361)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:328)
        at org.antlr.v4.Tool.main(Tool.java:172)
```

**Comment by hagen666** [comment]
The antlr version is 4.7.2.

**Comment by ericvergnaud** [comment]
Hi,
thanks but without a simple way to reproduce, this is unlikely to raise any attention.

**Comment by hagen666** [comment]
A running example is here:
https://s3.amazonaws.com/artifacts.opencypher.org/Cypher.g4
it is the openCypher grammar.

**Comment by ericvergnaud** [comment]
Seems that grammar accepts bytes that are not valid Java code points?
Suggest you track which exact node names trigger the exception.

**Comment by hagen666** [comment]
Is it means that i need to clone the antlr repo and debug it in Eclipse?

**Comment by hagen666** [comment]
But it runs well when using antlr to parse the grammar.

**Comment by ericvergnaud** [comment]
> Is it means that i need to clone the antlr repo and debug it in Eclipse?

No just launch the cmd line with a java debugger

**Comment by ericvergnaud** [comment]
> But it runs well when using antlr to parse the grammar.

The exception occurs as a result of using -atn option, which is used to generate a diagram, and I believe happens after the parser is generated

**Comment by sharwell** [comment]
I'm guessing `atom.label` is evaluating to -1, but this would occur for any negative value or for any value greater than 0x10FFFF.

**Comment by wadoon** [comment]
I had the same error with [KeYLexer.g4](https://github.com/KeYProject/key/blob/main/key.core/src/main/antlr4/KeYLexer.g4) and [KeYParser.g4](https://github.com/KeYProject/key/blob/main/key.core/src/main/antlr4/KeYParser.g4). 

I could pinpoint it to the appearance of the token `EOF` in lexer and parser grammar, e.g., 

```
file: DOC_COMMENT* (profile? preferences? decls problem? proof?) EOF;
```

**Comment by kaby76** [comment]
EOF should probably not be used in a lexer rule. What does the "EOF" character look like in the token text for a DOC_COMMENT? Is there a Unicode character for EOF? Consider replacing it with an empty rule with a predicate that returns true if an EOF is reached on the char stream. `DOC_COMMENT_END: ('*/'| { this.TestEOF() }? ) -> type(DOC_COMMENT), popMode;`.
