### ISSUE TITLE
java.lang.NullPointerException at org.antlr.v4.runtime.misc.Utils.escapeWhitespace

### ISSUE THREAD

**Issue by evnix** [antlr/antlr4#2677]
Grammar used (PHP 7):  https://github.com/antlr/grammars-v4/tree/master/php
Antlr version: 4.7.2

```
java.lang.NullPointerException
	at org.antlr.v4.runtime.misc.Utils.escapeWhitespace(Utils.java:63)
	at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:49)
	at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
	at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
	at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
	at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
	at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
	at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
	at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:42)
	at org.antlr.v4.runtime.RuleContext.toStringTree(RuleContext.java:191)
	at com.t.php.PHPLanguage.execute(PHPLanguage.java:72)
	at com.t.php.PHPLanguageTest.execute(PHPLanguageTest.java:16)

```
passing test code
```java
    @Test
    public void execute() throws Exception {
        PHPLanguage phpLanguage = new PHPLanguage();
        String test=  "<?php  $t=1;?>";
        phpLanguage.execute(null, new ByteArrayInputStream(test.getBytes()));
    }
```

failing test code (difference is the space after semicolon in test string)
```java
    @Test
    public void execute() throws Exception {
        PHPLanguage phpLanguage = new PHPLanguage();
        String test=  "<?php  $t=1; ?>";
        phpLanguage.execute(null, new ByteArrayInputStream(test.getBytes()));
    }
```

```java
public final class PHPLanguage{

    public void execute(String path, InputStream stream) throws Exception{
        CharStream codePointCharStream = CharStreams.fromStream(stream);
        PhpLexer phpLexer = new PhpLexer(codePointCharStream);
        CommonTokenStream tokens = new CommonTokenStream(phpLexer);
        PhpParser phpParser = new PhpParser(tokens);
        ParseTree tree = phpParser.htmlDocument();
//        new PhpParserBaseVisitorImpl().visit(tree);
        System.out.println(tree.toStringTree(phpParser));
    }

}

```

```java

public abstract class PhpBaseLexer extends Lexer
{
    protected boolean AspTags = true;
    protected boolean _scriptTag;
    protected boolean _styleTag;
    protected String _heredocIdentifier;
    protected int _prevTokenType;
    protected String _htmlNameText;
    protected boolean _phpScript;
    protected boolean _insideString;

    public PhpBaseLexer(CharStream input) {
        super(input);
    }

    @Override
    public Token nextToken() {
        CommonToken token = (CommonToken)super.nextToken();

        if (token.getType() == PhpLexer.PHPEnd || token.getType() == PhpLexer.PHPEndSingleLineComment)
        {
            if (_mode == PhpLexer.SingleLineCommentMode)
            {
                // SingleLineCommentMode for such allowed syntax:
                // <?php echo "Hello world"; // comment ?>
                popMode(); // exit from SingleLineComment mode.
            }
            popMode(); // exit from PHP mode.

            if (token.getText().equals("</script>"))
            {
                _phpScript = false;
                token.setType(PhpLexer.ScriptClose);
            }
            else
            {
                // Add semicolon to the end of statement if it is absente.
                // For example: <?php echo "Hello world" ?>
                if (_prevTokenType == PhpLexer.SemiColon || _prevTokenType == PhpLexer.Colon
                        || _prevTokenType == PhpLexer.OpenCurlyBracket || _prevTokenType == PhpLexer.CloseCurlyBracket)
                {
                    token.setChannel(PhpLexer.SkipChannel);
                }
                else
                {
                    token = new CommonToken(PhpLexer.SemiColon);
                }
            }
        }
        else if (token.getType() == PhpLexer.HtmlName)
        {
            _htmlNameText = token.getText();
        }
        else if (token.getType() == PhpLexer.HtmlDoubleQuoteString)
        {
            if (token.getText().equals("php") && _htmlNameText.equals("language"))
            {
                _phpScript = true;
            }
        }
        else if (_mode == PhpLexer.HereDoc)
        {
            // Heredoc and Nowdoc syntax support: http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc
            switch (token.getType())
            {
                case PhpLexer.StartHereDoc:
                case PhpLexer.StartNowDoc:
                    _heredocIdentifier = token.getText().substring(3).trim().replace("\'","");
                    break;

                case PhpLexer.HereDocText:
                    if (CheckHeredocEnd(token.getText()))
                    {
                        popMode();

                        String heredocIdentifier = GetHeredocIdentifier(token.getText());
                        if (token.getText().trim().endsWith(";"))
                        {
                            token = new CommonToken(PhpLexer.SemiColon, heredocIdentifier + ";\n");
                        }
                        else
                        {
                            token = (CommonToken)super.nextToken();
                            token.setText(heredocIdentifier + "\n;");
                        }
                    }
                    break;
            }
        }
        else if (_mode == PhpLexer.PHP)
        {
            if (_channel != HIDDEN)
            {
                _prevTokenType = token.getType();
            }
        }

        return token;
    }

    private String GetHeredocIdentifier(String text) {
        String trimmedText = text.trim();
        boolean semi = (trimmedText.length() > 0) ? (trimmedText.charAt(trimmedText.length() - 1) == ';') : false;
        return semi ? trimmedText.substring(0, trimmedText.length() - 1) : trimmedText;
    }

    private boolean CheckHeredocEnd(String text) {
        return GetHeredocIdentifier(text).equals(_heredocIdentifier);
    }

    protected boolean IsNewLineOrStart(int pos) {
        return this._input.LA(pos) <= 0 || this._input.LA(pos) == '\r' || this._input.LA(pos) == '\n';
    }

    protected void PushModeOnHtmlClose() {
        popMode();
        if (_scriptTag)
        {
            if (!_phpScript)
            {
                pushMode(PhpLexer.SCRIPT);
            }
            else
            {
                pushMode(PhpLexer.PHP);
            }
            _scriptTag = false;
        }
        else if (_styleTag)
        {
            pushMode(PhpLexer.STYLE);
            _styleTag = false;
        }
    }

    protected boolean HasAspTags() {
        return this.AspTags;
    }

    protected boolean HasPhpScriptTag() {
        return this._phpScript;
    }

    protected void PopModeOnCurlyBracketClose() {
        if (_insideString)
        {
            _insideString = false;
            setChannel(PhpLexer.SkipChannel);
            popMode();
        }
    }

    protected boolean ShouldPushHereDocMode(int pos) {
        return _input.LA(pos) == '\r' || _input.LA(pos) == '\n';
    }

    protected boolean IsCurlyDollar(int pos) {
        return _input.LA(pos) == '$';
    }

    protected void SetInsideString() {
        _insideString = true;
    }
}
```

**Comment by RossPatterson** [comment]
This is still a bug as of 4.11.1, and can be generated without any user-supplied code.  Simply build the `grammars-v4/php` parser for the Java target and run `grun Php htmlDocument -tree ..\examples\alternativeSyntax.php`.  It actually fails for all of the files in the `grammars-v4/php/examples` directory.  I discovered this when [`grammars-v4` PR #2842](https://github.com/antlr/grammars-v4/pull/2842) failed all the `build-pwsh(*,Java)` CI jobs.
