### ISSUE TITLE
cpp target: NoviableException caused a coredump error

### ISSUE THREAD

**Issue by small-cat** [antlr/antlr4#2702]
I encounter an error when parsing hql by antlr4. The parser file is [here](https://github.com/small-cat/myCode_repository/blob/master/antlr4_cpp/hive/HqlsqlParser.g4). When I parse the following sql

```sql
select * from myinput1_n9 a join myinput1_n9 b on a.key<=>b.value;
```

program will cause a segmentation fault. The debug information is

```
#0  0x000055d94ae38ef0 in ?? ()
No symbol table info available.
#1  0x000055d94980daee in antlr4::NoViableAltException::~NoViableAltException (this=0x55d94ae15ad0, __in_chrg=<optimized out>)
    at /home/jona/myGit/myCode_repository/antlr4_cpp/runtime/src/NoViableAltException.cpp:25
No locals.
#2  0x000055d9498bd8d2 in std::__exception_ptr::__dest_thunk<antlr4::NoViableAltException> (__x=0x55d94ae15ad0)
    at /usr/include/c++/7/bits/exception_ptr.h:172
No locals.
#3  0x00007f21afcdd8c1 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x000055d9498bb729 in antlr4::DefaultErrorStrategy::reportNoViableAlternative (this=0x55d94ac438e0, recognizer=0x7ffcd1bde3d0, e=...)
    at /home/jona/myGit/myCode_repository/antlr4_cpp/runtime/src/DefaultErrorStrategy.cpp:148
        tokens = 0x7ffcd1bde260
        input = "from myinput1_n9 a join myinput1_n9 b on a.key<=>"
        msg = "no viable alternative at input 'from myinput1_n9 a join myinput1_n9 b on a.key<=>'"
#5  0x000055d9498bae0d in antlr4::DefaultErrorStrategy::reportError (this=0x55d94ac438e0, recognizer=0x7ffcd1bde3d0, e=...)
    at /home/jona/myGit/myCode_repository/antlr4_cpp/runtime/src/DefaultErrorStrategy.cpp:65
No locals.
#6  0x000055d9496f443a in HqlsqlParser::subselect_stmt (this=0x7ffcd1bde3d0)
    at /home/jona/myGit/myCode_repository/antlr4_cpp/hive/generated/HqlsqlParser.cpp:30004
        e = @0x55d94ae0a940: {
          <antlr4::RuntimeException> = {
            <std::exception> = {<No data fields>}, 
            members of antlr4::RuntimeException: 
            _message = "No viable alternative"
          }, 
          members of antlr4::RecognitionException: 
          _recognizer = 0x7ffcd1bde3d0, 
          _input = 0x7ffcd1bde260, 
          _ctx = 0x55d94ad27bf0, 
          _offendingToken = 0x55d94ad1e080, 
          _offendingState = 3408
        }
        _localctx = 0x55d94ad27bf0
---Type <return> to continue, or q <return> to quit---
        _la = 262
        onExit = {
          _cleanUp = {
            <std::_Maybe_unary_or_binary_function<void>> = {<No data fields>}, 
            <std::_Function_base> = {
              static _M_max_size = 16, 
              static _M_max_align = 8, 
              _M_functor = {
                _M_unused = {
                  _M_object = 0x7ffcd1bde3d0, 
                  _M_const_object = 0x7ffcd1bde3d0, 
                  _M_function_pointer = 0x7ffcd1bde3d0, 
                  _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x7ffcd1bde3d0, this adjustment 94391729454306
                }, 
                _M_pod_data = "\320\343\275\321\374\177\000\000\342\374\200I\331U\000"
              }, 
              _M_manager = 0x55d949751186 <std::_Function_base::_Base_manager<HqlsqlParser::subselect_stmt()::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>
            }, 
            members of std::function<void()>: 
            _M_invoker = 0x55d949751163 <std::_Function_handler<void(), HqlsqlParser::subselect_stmt()::<lambda()> >::_M_invoke(const std::_Any_data &)>
          }, 
          _enabled = true
        }
...
```

After reading the source code, I found that,  in file `ParserATNSimulator.cpp:179`,  

```c++
      NoViableAltException e = noViableAlt(input, outerContext, previousD->configs.get(), startIndex, false);
      input->seek(startIndex);                                                       
      size_t alt = getSynValidOrSemInvalidAltThatFinishedDecisionEntryRule(previousD->configs.get(), outerContext);
      if (alt != ATN::INVALID_ALT_NUMBER) {                                          
        return alt;                                                                  
      }                                                                              
                                                                                     
      throw e;    
```

when I debug into here, program will be ok and throw NoViableException correctly. The last argument in function `noViableAlt` is false. But when I debug into `ParserATNSimulator.cpp:354`， the code is 

```
NoViableAltException e = noViableAlt(input, outerContext, previous, startIndex, previous != s0);
      input->seek(startIndex);                                                       
      size_t alt = getSynValidOrSemInvalidAltThatFinishedDecisionEntryRule(previous, outerContext);
      if (alt != ATN::INVALID_ALT_NUMBER) {                                          
        return alt;                                                                  
      }                                                                              
      throw e; 
```

in my program,  `previous != s0`, so the last argument in function `noViable` is true, and in `NoViableAltException.cpp:23`

```
NoViableAltException::~NoViableAltException() {                                     
  if (_deleteConfigs)                                                               
    delete _deadEndConfigs;                                                         
} 
```

if `_deleteConfigs` is true, the destructure will delete `_deadEndConfigs`, but in `ParserATNSimulator.cpp:354`, it will also destruct in the end. This will cause double free error.

If I change `ParserATNSimulator.cpp:354` to 

```
NoViableAltException e = noViableAlt(input, outerContext, previous, startIndex, false);
```

program will be ok and don't cause coredump error.

I am a new to antlr4, I don't know whether the point I found is the problem or not, maybe someone can fix it?

**Comment by small-cat** [comment]
I try with 4.9.2, and found this problem had been fixed.
