### ISSUE TITLE
Problem in PredictionContext while executing parser (javascript target)

### ISSUE THREAD

**Issue by elliarbtan** [antlr/antlr4#2713]
Using following npm packages for antlr4 antrl4-tools

` "antlr4": "^4.7.2",`
` "antlr4-tool": "^1.0.26"` (antlr4-tool packages antlr-tools 4.7.1)

This grammar does not yield an usable parser
```
expression : s2 ;
s2 : P* anyc+;
anyc : A  | P ;
A : 'a' ;
P : 'p' ;
```

when the expression parser in called, it throws  :

```
TypeError: Cannot read property 'EMPTY' of undefined
    at predictionContextFromRuleContext ([...]node_modules/antlr4/PredictionContext.js:293:70)
    at ParserATNSimulator.computeStartState ([...]node_modules/antlr4/atn/ParserATNSimulator.js:873:26)
    at ParserATNSimulator.execATN ([...]node_modules/antlr4/atn/ParserATNSimulator.js:468:35)
    at ParserATNSimulator.adaptivePredict ([...]node_modules/antlr4/atn/ParserATNSimulator.js:361:24)
    at XxxYyyParser.s2 ([...]tmp/grammaroutput/XxxYyyParser.js:205:33)
    at XxxYyyParser.expression ([...]tmp/grammaroutput/XxxYyyParser.js:117:14)
```

this grammar, where s2 is replaced by its definition, does not fail when parsed
```

expression : P* anyc+;
anyc : A  | P ;
A : 'a' ;
P : 'p' ;

```
I think both grammar are correct, as the Antlr debug tools shows a correct parse tree for them.

**Comment by ericvergnaud** [comment]
This could be an issue with the tool you are using which is not the official tool.
If you don’t need TS support, suggest you switch to the official tool.
Otherwise, maybe check with that tool's author: mcchatman8009

**Comment by elliarbtan** [comment]
Thank you.

As antlr4-tool was not needed, I removed it and used the 4.7.2 jar from official site: same problem. It turns out the parse error, happening on Parser.parse() happens only when the following (unneeded) import is present : `import { Trees } from 'antlr4/tree/Trees.js'`

I don't understand why, anyway you can close this issue.
Thanks.
