### ISSUE TITLE
UnsupportedOperationException while generating code for large grammars.

### ISSUE THREAD

**Issue by mimuogi** [antlr/antlr4#2732]
When generating code for large grammars we are getting this exception log. The code generation targets C#.

Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element 85257 element 11 out of range 0..65535
  	at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:362)
  	at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
  	at org.antlr.v4.Tool.generateInterpreterData(Tool.java:745)
  	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
  	at org.antlr.v4.Tool.process(Tool.java:361)
  	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:328)
  	at org.antlr.v4.Tool.main(Tool.java:172)
  
  
  UserGrammar.g4

**Comment by KvanTTT** [comment]
What runtime have you tried? [Official](https://github.com/antlr/antlr4/blob/master/doc/csharp-target.md) (this) or [optimized](https://github.com/tunnelvisionlabs/antlr4cs) by @sharwell?

Also, could you attach your grammar where such an exception occurs?

**Comment by mimuogi** [comment]
> What runtime have you tried? Official (this) or optimized by @sharwell?
> Also, could you attach your grammar where such an exception occurs?

I tried the [official](https://github.com/antlr/antlr4/blob/master/doc/csharp-target.md) runtime. For privacy reasons I can't share the grammar at the issue and I had contact you through your email. Thank you for your help.

**Comment by JenniferPruitt** [comment]
I noticed that there is a similar problem at https://github.com/antlr/antlr4/issues/840. Perhaps we can refer to [this issue](https://github.com/antlr/antlr4/issues/840) to find more context about the bug.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/3591
