### ISSUE TITLE
Python3 target crashes on AttributeError: 'str' object has no attribute 'mark'

### ISSUE THREAD

**Issue by XsongyangX** [antlr/antlr4#2743]
I tried to write a simple parser in Python 3 with the following grammar:
```
// Define a grammar called Sentences
grammar Sentences;
start : sentence (Delimiters sentence)*;
sentence : Word (Space Word)* | ;

// Sentences are separated by '.', '!' or '?'
Delimiters : '.' | '?' | '!' ;
Word : [A-Za-z0-9]+ ;
Space : [ \t\r\n]+ -> skip;
```
Everything works as expected in the Java target. Then I made this `Main.py` script to run the parser generated by `antlr4 Sentences.g4 -Dlanguage=Python3`:
(inspired by [this tutorial](https://dzone.com/articles/using-antlr-4-with-python-2))
```python3
import sys
from antlr4 import *
from SentencesLexer import SentencesLexer
from SentencesParser import SentencesParser
from SentencesListener import SentencesListener

class TestPrintListener(SentencesListener):
    def enterStart(self, ctx):
        print(f"Enter start: {ctx.ID()}")

def main(argv):
    inputv = input()
    lexer = SentencesLexer(inputv)
    stream = CommonTokenStream(lexer)
    parser = SentencesParser(stream)
    tree = parser.start()
    printer = TestPrintListener()
    walker = ParseTreeWalker()
    walker.walk(printer, tree)
 
if __name__ == '__main__':
    main(sys.argv)
```
Running `Main.py` yields this `AttributeError`. Here is the log:
```
$ python Main.py
hello
Traceback (most recent call last):
  File "Main.py", line 22, in <module>
    main(sys.argv)
  File "Main.py", line 16, in main
    tree = parser.start()
  File "C:\Users\Song\Documents\Scripts\Python Scripts\parsing\SentencesParser.py", line 74, in start
    self.enterRule(localctx, 0, self.RULE_start)
  File "C:\Users\Song\Anaconda3\lib\site-packages\antlr4\Parser.py", line 366, in enterRule
    self._ctx.start = self._input.LT(1)
  File "C:\Users\Song\Anaconda3\lib\site-packages\antlr4\CommonTokenStream.py", line 61, in LT
    self.lazyInit()
  File "C:\Users\Song\Anaconda3\lib\site-packages\antlr4\BufferedTokenStream.py", line 186, in lazyInit
    self.setup()
  File "C:\Users\Song\Anaconda3\lib\site-packages\antlr4\BufferedTokenStream.py", line 189, in setup
    self.sync(0)
  File "C:\Users\Song\Anaconda3\lib\site-packages\antlr4\BufferedTokenStream.py", line 111, in sync
    fetched = self.fetch(n)
  File "C:\Users\Song\Anaconda3\lib\site-packages\antlr4\BufferedTokenStream.py", line 123, in fetch
    t = self.tokenSource.nextToken()
  File "C:\Users\Song\Anaconda3\lib\site-packages\antlr4\Lexer.py", line 111, in nextToken
    tokenStartMarker = self._input.mark()
AttributeError: 'str' object has no attribute 'mark'
```

**Comment by ericvergnaud** [comment]
The lexer expects a stream, not a string, as input.
please close

**Comment by XsongyangX** [comment]
Ok thanks
