### ISSUE TITLE
SyntaxError in python3 when using Java9 grammer

### ISSUE THREAD

**Issue by jayendra13** [antlr/antlr4#2763]
I have downloaded the jar file of the antlr from the home page antlr website, installed the python3 runtime for antlr and got the grammar of Java9 for antlr version4 from here.

I am generating the lexer and parser with the jar for the python3 target with.
```
java -jar antlr-4.8-complete.jar -Dlanguage=Python3 grammars/java/Java9.g4
```
It is working as expected and making lexer and parser for the python3.

WhenI try to import the lexer I get the syntax error.
```
ipython
Python 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from Java9Lexer import Java9Lexer                                                                                                                                                                                                     
Traceback (most recent call last):

  File "/Users/jayendrap/PycharmProjects/.venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-7a8e8e307f9b>", line 1, in <module>
    from Java9Lexer import Java9Lexer

  File "/Users/jayendrap/java/grammars/java/Java9Lexer.py", line 793
    return Character.isJavaIdentifierStart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))
                                                                            ^
SyntaxError: invalid syntax
```

**Comment by ericvergnaud** [comment]
That grammar only works with Java.
Please get support from the google discussion group.
