### ISSUE TITLE
NullPointerException in Java with small grammar

### ISSUE THREAD

**Issue by yaagma** [antlr/antlr4#2767]
This is the input:
```
person.age
```

And this is the grammar:

```antlr
start	: expr EOF { System.out.println($expr.txt); };

expr returns[String txt]
	: IDENT			{ $txt = $IDENT.text; }
	| l=expr '+' r=expr	{ $txt = $l.txt + '+' + $r.txt; }
	| expr '.' IDENT	{ $txt = $expr.txt + '.' +  $IDENT.text; } // <-- Exception in $expr.txt
	// | e=expr '.' IDENT 	{ $txt = $e.txt + '.' +  $IDENT.text; }  // Fixed rule
	;

IDENT: [a-zA-Z]+;
WS: [ \r\n]+ -> skip	;
```

ANLTR compiles without problems, but when executing the resulting Java Parser:
```
Exception in thread "main" java.lang.NullPointerException
        at parser.GrammarParser.expr(GrammarParser.java:204)
        at parser.GrammarParser.start(GrammarParser.java:111)
        at main.Main.compile(Main.java:54)
        at main.Main.main(Main.java:35)
```

Everything works if I use a label:
```antlr
expr returns[String txt]
	: IDENT			{ $txt = $IDENT.text; }
	| l=expr '+' r=expr	{ $txt = $l.txt + '+' + $r.txt; }
	// | expr '.' IDENT	{ $txt = $expr.txt + '.' +  $IDENT.text; } // <-- Exception in $expr.txt
	| e=expr '.' IDENT 	{ $txt = $e.txt + '.' +  $IDENT.text; } // Fixed rule
	;
```

Is this a bug? I prefer to avoid labels if possible to keep rules clean.
 
Thanks

**Comment by XsongyangX** [comment]
This is strange. It's like if ANTLR confuses the left hand side of the rule with the right hand side when the rule is used recursively. This might be a bug, but it would be nice if it can be used like in your example.

**Comment by durkpolish** [comment]
Null point in java is very small point most of people ignore this one but some of people get it so don't be do this which harmful for your code files. https://www.myapklab.com/aqua-liker-apk/
