### ISSUE TITLE
NullReferenceException in C# target after a token injection

### ISSUE THREAD

**Issue by RobEin** [antlr/antlr4#2783]
Hi,
I'm working on a Python parser that insert INDENT/DEDENT and NEWLINE tokens and encountered the following error in the generated parser.

The stripped down Python3 grammar:
```antlr
grammar Python3; // stripped down version
tokens { INDENT, DEDENT }

file_input : (NEWLINE | stmt)* EOF;

stmt : simple_stmt | compound_stmt;
simple_stmt : small_stmt NEWLINE;
small_stmt : assignment_stmt | flow_stmt;
assignment_stmt : NAME '=' expr;
flow_stmt: BREAK | CONTINUE;

compound_stmt: while_stmt;
while_stmt: 'while' test ':' suite;
suite : simple_stmt | NEWLINE INDENT stmt+ DEDENT;

test : expr (comp_op expr)*;
comp_op : '<' | '>' | '==' | '>=' | '<=' | '!=';
expr : expr (( '+' | '-' ) expr)+ | NAME | NUMBER | '(' expr ')';

BREAK: 'break';
CONTINUE: 'continue';
NUMBER : DECIMAL_INTEGER;
NEWLINE : ( '\r'? '\n' | '\r' | '\f' ) SPACES?;
NAME : ID_START ID_CONTINUE*;
DECIMAL_INTEGER : NON_ZERO_DIGIT DIGIT* | '0'+;
SKIP_ : ( SPACES | COMMENT ) -> skip;

fragment NON_ZERO_DIGIT : [1-9];
fragment DIGIT : [0-9];
fragment SPACES : [ \t]+;
fragment COMMENT : '#' ~[\r\n\f]*;
fragment ID_START : '_' | [A-Z] | [a-z];
fragment ID_CONTINUE : ID_START | [0-9];
```

The C# code that includes a bad Python code (no indent) and after the token insertion throws a NullReferenceException. (otherwise, in Java target there is no exception)
```csharp
static void Main(string[] args)
{
	var input = CharStreams.fromstring("while i == 1:\r\n" +
	                                   "break"); // no INDENT and no NEWLINE

	var lexer  = new TokenInjector(input);
	var tokens = new CommonTokenStream(lexer);
	var parser = new Python3Parser(tokens);
	parser.file_input();
}

class TokenInjector : Python3Lexer
{
	private bool isNewLineNeeded = true;

	public TokenInjector(ICharStream input) : base(input) { }
	public override IToken NextToken() 
	{
		IToken currentToken = base.NextToken();
		if (currentToken.Type == Eof && isNewLineNeeded)
		{
			isNewLineNeeded = false;
			return new CommonToken(NEWLINE, "<inserted newline>");
		}
		else
		{
			return currentToken;
		}
	}
}
```

An other C# code that includes a correct Python code and runs without problem:
```csharp
static void Main(string[] args)
{
	var input = CharStreams.fromstring("while i == 1:\r\n" +
	                                   "    break"); // no NEWLINE

	var lexer  = new TokenInjector(input);
	var tokens = new CommonTokenStream(lexer);
	var parser = new Python3Parser(tokens);
	parser.file_input();

	Console.WriteLine(input.ToString());
	Console.WriteLine();
	foreach (IToken t in tokens.GetTokens())
	{
		Console.WriteLine(t.ToString());
	}
	Console.ReadKey();
}

class TokenInjector : Python3Lexer
{
	private bool isIndentNeeded  = true;
	private bool isBreakNeeded   = true;
	private bool isNewLineNeeded = true;
	private bool isDedentNeeded  = true;

	public TokenInjector(ICharStream input) : base(input) { }
	public override IToken NextToken()
	{
		IToken currentToken = base.NextToken();
		if (currentToken.Type == Python3Parser.BREAK && isIndentNeeded)
		{
			isIndentNeeded = false;
			return new CommonToken(Python3Parser.INDENT, "<inserted indent>");
		}
		else if (currentToken.Type == Eof && isBreakNeeded)
		{
			isBreakNeeded = false;
			return new CommonToken(Python3Parser.BREAK, "<break>");
		}
		else if (currentToken.Type == Eof && isNewLineNeeded)
		{
			isNewLineNeeded = false;
			return new CommonToken(NEWLINE, "<inserted newline>");
		}
		else if (currentToken.Type == Eof && isDedentNeeded)
		{
			isDedentNeeded = false;
			return new CommonToken(Python3Parser.DEDENT, "<inserted dedent>");
		}
		else
		{
			return currentToken;
		}
	}
}
```

The error message:
```text
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Antlr4.Runtime.Standard
  StackTrace:
   at Antlr4.Runtime.DefaultErrorStrategy.ConstructToken(ITokenSource tokenSource, Int32 expectedTokenType, String tokenText, IToken current)
   at Antlr4.Runtime.DefaultErrorStrategy.GetMissingSymbol(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.RecoverInline(Parser recognizer)
   at Antlr4.Runtime.Parser.Match(Int32 ttype)
   at Python3Parser.suite() in C:\......................\Python3Parser.cs:line 672
   at Python3Parser.while_stmt() in C:\......................\Python3Parser.cs:line 595
   at Python3Parser.compound_stmt() in C:\......................\Python3Parser.cs:line 465
   at Python3Parser.stmt() in C:\......................\Python3Parser.cs:line 217
   at Python3Parser.file_input() in C:\......................\Python3Parser.cs:line 150
   at ConsoleApp29.Program.Main(String[] args) in C:\......................\Program.cs:line 16
```

Thanks,
Robert

**Comment by d-markey** [comment]
You're consuming a token with `base.NextToken()` and discard it when you insert the `NEWLINE `token. Maybe you should keep the token in memory and return it the next time `NextToken()` is called.

**Comment by RobEin** [comment]
Thank you for your reply.
What do you mean to keep in memory?
If I don't discard the EOF token and return with it, the reading of the input stream will be stopped and after that there will be no next time to insert any token.

Approached on the other hand, if I discard the EOF token and return with another token, the input stream will not be stopped and after that only EOF tokens come until the first returning EOF.
At least that's how it works in Java target in my experience.

**Comment by d-markey** [comment]
I mean something like

```
class TokenInjector : Python3Lexer
{
	private bool isNewLineNeeded = true;
	private IToken consumedToken = null;

	public TokenInjector(ICharStream input) : base(input) { }
	public override IToken NextToken() 
	{
		if (consumedToken != null) {
			/* ensure last read token is not removed from the stream */
			var token = consumedToken;
			consumedToken = null;
			return token;
		}
		IToken currentToken = base.NextToken();
		if (currentToken.Type == Eof && isNewLineNeeded)
		{
			isNewLineNeeded = false;
			consumedToken = currentToken; /* remember this token for the next call */
			return new CommonToken(NEWLINE, "<inserted newline>");
		}
		else
		{
			return currentToken;
		}
	}
}
```

**Comment by RobEin** [comment]
Thanks for the suggestion, but unfortunately I have the same exception thrown in this code.
Does it work for you?

**Comment by d-markey** [comment]
Works with this:

```
			...
			if (currentToken.Type == Eof && isNewLineNeeded)
			{
				prevToken = currentToken;
				isNewLineNeeded = false;
				var tokenSource = currentToken.TokenSource;
				var factory = tokenSource.TokenFactory;
				return factory.Create(Tuple.Create(tokenSource, tokenSource.InputStream), NEWLINE, "<inserted new line>", TokenConstants.DefaultChannel, -1, -1, currentToken.Line, currentToken.Column);
			}
			else
			...
```

You're creating a token out-of-context, and the DefaultErrorStrategy() method requires a TokenSource from your token. It is null when you instantiate a token with `new CommonToken()`. I don't know why the Java version works better.

**Comment by RobEin** [comment]
That's great.
It works.
Thanks for the help.
