### ISSUE TITLE
JavaScript examples don't run. antlr4/index is missing

### ISSUE THREAD

**Issue by brakmic** [antlr/antlr4#2846]
I am trying to execute the JavaScript examples but they always crash with the same error message:

```shell
> node ./test1.js

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'antlr4/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (c:\bin\antlr4\grammar\MySyntaxLexer.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

I'm using Node 10 and npm 5.6.0 on a Windows 10 x64.

antlr `npm package` is properly installed.

**Comment by brakmic** [comment]
Ok, I think I found the problem: my *grammar directory* was outside the project path, because I intended to write several apps that access the same grammar.

Maybe one could put it somewhere in the docs (if not already stated somewhere). 

Regards,
