### ISSUE TITLE
Possible JS bug? TypeError: Cannot read property 'hashCode' of null

### ISSUE THREAD

**Issue by MartinPavlik** [antlr/antlr4#2924]
Hi,

I hit the following error while trying to parse my grammar. I'm running version 4.8.0.

## Error:
```
/home/martin/work/antlr4-example/QueryLangParser.js:242
                throw re;
                ^

TypeError: Cannot read property 'hashCode' of null
    at Map.standardHashCodeFunction [as hashFunction] (/home/martin/work/antlr4-example/node_modules/antlr4/Utils.js:74:14)
    at Map.containsKey (/home/martin/work/antlr4-example/node_modules/antlr4/Utils.js:243:34)
    at combineCommonParents (/home/martin/work/antlr4-example/node_modules/antlr4/PredictionContext.js:650:23)
    at mergeArrays (/home/martin/work/antlr4-example/node_modules/antlr4/PredictionContext.js:633:2)
    at merge (/home/martin/work/antlr4-example/node_modules/antlr4/PredictionContext.js:342:9)
    at mergeArrays (/home/martin/work/antlr4-example/node_modules/antlr4/PredictionContext.js:572:24)
    at merge (/home/martin/work/antlr4-example/node_modules/antlr4/PredictionContext.js:342:9)
    at mergeArrays (/home/martin/work/antlr4-example/node_modules/antlr4/PredictionContext.js:572:24)
    at merge (/home/martin/work/antlr4-example/node_modules/antlr4/PredictionContext.js:342:9)
    at ATNConfigSet.add (/home/martin/work/antlr4-example/node_modules/antlr4/atn/ATNConfigSet.js:107:15)
```

## Steps to reproduce
I created a repo where you can try this, please check https://github.com/MartinPavlik/mtg-query-language-parser-antlr4. Important files are `QueryLang.g4` and `index.js`.

Running
```
npm i;
node index.js;
```
should give you the same error as I got. 

## How to "fix" it

In `node_modules/antlr4/Utils.js` I changed the following lines from:
```js
function standardEqualsFunction(a, b) {
    return a.equals(b);
}

function standardHashCodeFunction(a) {
    return a.hashCode();
}
```

to:
```js
function standardEqualsFunction(a, b) {
    return a ? a.equals(b) : a === b;
}

function standardHashCodeFunction(a) {
    return a ? a.hashCode() : '';
}
```
and it started working as I expected. 

Am I doing something wrong or this is a bug?

**Comment by MartinPavlik** [comment]
Ah, I see that it is already fixed in master, closing this.

https://github.com/antlr/antlr4/blob/master/runtime/JavaScript/src/antlr4/Utils.js
