### ISSUE TITLE
NodeJS 14.15.0 - Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

### ISSUE THREAD

**Issue by gizmodus** [antlr/antlr4#2951]
After updating to NodeJS 14.15.0, I see the following warning (we use Webpack 5.4.0):

```
(node:8744) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object.<anonymous> (***\node_modules\antlr4\RuleContext.js:30:46)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (***\node_modules\antlr4\PredictionContext.js:8:19)
```

**Comment by ericvergnaud** [comment]
Hi,
already fixed, pending release.
Thanks

**Comment by gizmodus** [comment]
@ericvergnaud Great, thank you!
