### ISSUE TITLE
Over-escaping in char sets makes ANTLR 4.9 crash

### ISSUE THREAD

**Issue by andreasabel** [antlr/antlr4#3024]
See https://github.com/antlr/antlr4/issues/1537#issuecomment-753350342
I tried this on 4.9:
```
lexer grammar Issue1537;

CHAR : '\''   -> more, mode(CHARMODE);

mode CHARMODE;
CHARANY     :  ~[\'\\] -> more, mode(CHAREND);  // extra escaping of '

mode CHAREND;
CHARENDC     :  '\''  -> type(CHAR), mode(DEFAULT_MODE);
```
This makes ANTLR crash:
```
$ java org.antlr.v4.Tool Issue1537.g4
warning(156): Issue1537.g4:7:16: invalid escape sequence \'
Exception in thread "main" java.lang.RuntimeException: set is empty
	at org.antlr.v4.runtime.misc.IntervalSet.getMaxElement(IntervalSet.java:421)
	at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:169)
	at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
	at org.antlr.v4.Tool.generateInterpreterData(Tool.java:745)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
	at org.antlr.v4.Tool.process(Tool.java:369)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:328)
	at org.antlr.v4.Tool.main(Tool.java:172)
```
Ok, ANTLR should warn here as over-escaping isn't supported anymore since 4.6.
But for the sake of backwards-compatibility with 4.5, it should not crash, rather ignore the suprious `\`.
I think ANTLR crashing here was not the intention, see discussion at #1537.

**Comment by KvanTTT** [comment]
@parrt please close, it's fixed by https://github.com/antlr/antlr4/commit/7f07af85374383d877080fd97056977521056697 (error instead of warning).
