### ISSUE TITLE
JS error import antlr4 from 'antlr4';

### ISSUE THREAD

**Issue by quantrpeter** [antlr/antlr4#3088]
Hi
    when i 
```
import antlr4 from 'antlr4';
```

and node test.js, i got:
```
import antlr4 from 'antlr4';
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

package.json:
{
  "name": "js_test",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Peter <peter@quantr.hk>",
  "license": "Quantr Open Source License",
  "dependencies": {
    "antlr4": "4.8.0"
  }
}
```

please help
thanks

**Comment by ericvergnaud** [comment]
please get support from the google discussion group
