### ISSUE TITLE
Serialized ATN data element 810567 element 11 out of range 0..65535

### ISSUE THREAD

**Issue by ccrfrog** [antlr/antlr4#3338]
I have a `.g4` file in which one of the syntax rules has more than 80,000 alternatives,
when I run `antlr4 -Dlanguage=Go -visitor`
below exception occured

```
Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element 810567 element 11 out of range 0..65535
        at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:361)
        at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
        at org.antlr.v4.Tool.generateInterpreterData(Tool.java:745)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
        at org.antlr.v4.Tool.process(Tool.java:361)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:328)
        at org.antlr.v4.Tool.main(Tool.java:172)
```

**Comment by KvanTTT** [comment]
Out of curiosity: where do you need such a big number of alternatives?

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4/pull/3591
