### ISSUE TITLE
Antlr4 code generator throws exception under java 8

### ISSUE THREAD

**Issue by glebreutov** [antlr/antlr4#337]
I'm getting IndexOutOfBoundsException while trying to generate classes with Antlr Tool under Java 8.Under Java 7 same command with same grammar run's without issues. 

This command: 

``` cmd
java -cp antlr-4.1-complete.jar org.antlr.v4.Tool %* antlr4.bat MidasMain.g4 -package some.pkg.name  -visitor  -o ..\src\antlr4folder
```

Causes following exception: 

``` java
 Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at org.antlr.v4.misc.OrderedHashMap.getElement(OrderedHashMap.java:46)
        at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.setAltASTPointers(LeftRecursiveRuleTransformer.java:241)
        at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRule(LeftRecursiveRuleTransformer.java:162)
        at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRules(LeftRecursiveRuleTransformer.java:89)
        at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:94)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:399)
        at org.antlr.v4.Tool.process(Tool.java:384)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:343)
        at org.antlr.v4.Tool.main(Tool.java:190)
```

Issue can be reproduced with antlr 4.0 and antlr 4.1 under java 8

``` cmd
java version "1.8.0-ea"
Java(TM) SE Runtime Environment (build 1.8.0-ea-b108)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b50, mixed mode)
```

**Comment by javamonkey** [comment]
i get same error using antlrworks2

**Comment by Asnelchristian** [comment]
Hello, I am also getting the same error message; i am using java9 though.
