### ISSUE TITLE
dev version: using PredictionContextMergeCacheOptions::setMaxSize() causes crash

### ISSUE THREAD

**Issue by hzeller** [antlr/antlr4#3643]
Setting up a parser with a maximum merge cache size
```c++
  antlr4::atn::ParserATNSimulatorOptions options;
  options.setPredictionContextMergeCacheOptions(
    antlr4::atn::PredictionContextMergeCacheOptions()
    .setMaxSize(10000)
    .setClearEveryN(100));

  auto myParser  =new MyGeneratedParser(token_stream, options);
```

results in a crash in `moveToFront()`

```
0x0000555555c2254e in antlr4::atn::PredictionContextMergeCache::moveToFront (this=0x555557c20a58, entry=0x55555bfa4790)
    at antlr4/runtime/Cpp/runtime/src/atn/PredictionContextMergeCache.cpp:107
107       _head->prev = entry;
(gdb) bt
#0  0x0000555555c2254e in antlr4::atn::PredictionContextMergeCache::moveToFront (this=0x555557c20a58, entry=0x55555bfa4790)
    at antlr4/runtime/Cpp/runtime/src/atn/PredictionContextMergeCache.cpp:107
#1  0x0000555555c223e7 in antlr4::atn::PredictionContextMergeCache::get (this=0x555557c20a58, key1=..., key2=...)
    at antlr4/runtime/Cpp/runtime/src/atn/PredictionContextMergeCache.cpp:85
#2  0x0000555555c1473d in antlr4::atn::PredictionContext::mergeArrays (a=..., b=..., rootIsWildcard=true, mergeCache=0x555557c20a58)
    at antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.cpp:330
#3  0x0000555555c12c9a in antlr4::atn::PredictionContext::merge (a=..., b=..., rootIsWildcard=true, mergeCache=0x555557c20a58)
    at antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.cpp:210
#4  0x0000555555c14b99 in antlr4::atn::PredictionContext::mergeArrays (a=..., b=..., rootIsWildcard=true, mergeCache=0x555557c20a58)
    at antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.cpp:362
#5  0x0000555555c12c9a in antlr4::atn::PredictionContext::merge (a=..., b=..., rootIsWildcard=true, mergeCache=0x555557c20a58)
    at antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.cpp:210
#6  0x0000555555c5d075 in antlr4::atn::ATNConfigSet::add (this=0x55555bcc1220, config=..., mergeCache=0x555557c20a58)
    at antlr4/runtime/Cpp/runtime/src/atn/ATNConfigSet.cpp:64
#7  0x0000555555c02c47 in antlr4::atn::ParserATNSimulator::closure_ (this=0x555557c20a30, config=..., configs=0x55555bcc1220, closureBusy=..., collectPredicates=false, fullCtx=false, 
    depth=-5, treatEofAsEpsilon=false) at antlr4/runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp:891
#8  0x0000555555c02b85 in antlr4::atn::ParserATNSimulator::closureCheckingStopState (this=0x555557c20a30, config=..., configs=0x55555bcc1220, closureBusy=..., collectPredicates=false, 
    fullCtx=false, depth=-5, treatEofAsEpsilon=false) at antlr4/runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp:881
[.... looong stack trace ... ]
```

This is with breaking change mentioned #3641 already removed.

This only happens if `setMaxSize()` is set, just setting `setClearEveryN()` works.

**Comment by hzeller** [comment]
CC @jcking
