### ISSUE TITLE
NullPointerException in DefaultErrorStrategy.java

### ISSUE THREAD

**Issue by fredyvonvinet** [antlr/antlr4#3888]
I develop an interpreter for a new AI language inspired from Jason agent language.
This language is called Graal.
The parser is implemented with ANTLR 4 (4.10.1) in Java with grammar actions. When I run the generated ANTLR parser on a test graal file, I obtain a NullPointerException inside ANTLR code:

Exception in thread "main" java.lang.NullPointerException: Cannot read field "atn" because the return value of "org.antlr.v4.runtime.Parser.getInterpreter()" is null
            at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:231)
            at com.nemesis.cybercerberus.graal.GraalParser.agent(GraalParser.java:246)
            at com.nemesis.cybercerberus.graal.Graal.main(Graal.java:40)

I googleized the error message but no reference to this error has been met yet.
The project structure is joined and is Maven-based. The graal test file (test.graal) is included in the root directory. You can execute the project with the next commands:

   mvn exec:java

or

   mvn assembly:single
   java -jar target\graal-1.0-jar-with-dependencies.jar test.graal
[GRAAL.zip](https://github.com/antlr/antlr4/files/9566505/GRAAL.zip)

**Comment by fredyvonvinet** [comment]
The problem persists with release 4.11.1.

**Comment by fredyvonvinet** [comment]
The problem is solved. It does not come from action grammar code. It comes from my parser constructor (GraalParser(CommonTokenStream tokens)). It called super constructor but for initializing _interp I must call this((TokenStream) tokens).

So the bug came from my source code not from ANTLR. I close this issue that is not one.

**Comment by fredyvonvinet** [comment]
Error in my constructor.
