### ISSUE TITLE
Python runtime test failure with 4.10 and later

### ISSUE THREAD

**Issue by mweinelt** [antlr/antlr4#4041]
After upgrading the antlr4 python runtime past 4.9.1 (tested 4.10.1 and 4.11.1) in nixpkgs, we've been seeing its test suite fail with

```pytb
Traceback (most recent call last):
  File "/build/source/runtime/Python3/tests/ctest.py", line 10, in <module>
    from parser.cparser import CParser
  File "/build/source/runtime/Python3/tests/parser/cparser.py", line 631, in <module>
    class CParser ( Parser ):
  File "/build/source/runtime/Python3/tests/parser/cparser.py", line 635, in CParser
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/nix/store/ch8i929c63av55h9nxkinifh61mazf1h-python3.10-antlr4-python3-runtime-4.11.1/lib/python3.10/site-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
    self.checkVersion()
  File "/nix/store/ch8i929c63av55h9nxkinifh61mazf1h-python3.10-antlr4-python3-runtime-4.11.1/lib/python3.10/site-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
Exception: Could not deserialize ATN with version  (expected 4).
```

The version returned seems to be `\x03`, while the test suite expects it to be `4`.

While similar to #3997 and #3895 we are running the test suite, not our own code.

**Comment by mweinelt** [comment]
Looking at the test directory we should probably execute `run.py` instead. But then we get a version mismatch, even though we pass in the correct antlr4 version (4.11.1). Is the generation code version the python runtime tests against outdated? Is that a problem?

```
............
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
ANTLR runtime and generated code versions disagree: 4.11.1!=4.9.3
.
----------------------------------------------------------------------
Ran 16 tests in 0.031s

OK
```

**Comment by ericvergnaud** [comment]
Yes looks like the test samples need to be regenerated, and ran as part of our CI...
Would yo mind submitting a PR ?

**Comment by KvanTTT** [comment]
These tests should be either included into CI or removed. Otherwise, it's not clear why they are needed.

**Comment by mweinelt** [comment]
> Would yo mind submitting a PR ?

I'm unfamiliar with antlr unfortunately, only doing some cleanups in nixpkgs.
