### ISSUE TITLE
Insertion of new CommonToken(int type) in parse tree causes crash in toStringTree()

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4078]
This is a problem with the [grammars-v4/php](https://github.com/antlr/grammars-v4/tree/56dcd3d9251506d7514a68e86a4c192735c48f59/php) grammar, but in reality, it is a problem with the Antlr4 API since the API allows you to create a [CommonToken(int type) with a null text field](https://github.com/antlr/antlr4/blob/76fa05c21b12b96a6c12a0a82e611ed9d87d5af4/runtime/Java/src/org/antlr/v4/runtime/CommonToken.java#L87) and put it in a parse tree by returning the token via an overridden [nextToken()](https://github.com/antlr/antlr4/blob/76fa05c21b12b96a6c12a0a82e611ed9d87d5af4/runtime/Java/src/org/antlr/v4/runtime/Lexer.java#L112), which is what was done with this grammar.

When [toStringTree()](https://github.com/antlr/antlr4/blob/76fa05c21b12b96a6c12a0a82e611ed9d87d5af4/runtime/Java/src/org/antlr/v4/runtime/tree/Trees.java#L48) is called, the text for the token is attempted to be computed since it's a null value. But, instead, it crashes.
```
Exception in thread "main" java.lang.NullPointerException
        at org.antlr.v4.runtime.misc.Utils.escapeWhitespace(Utils.java:63)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:49)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:58)
        at org.antlr.v4.runtime.tree.Trees.toStringTree(Trees.java:42)
        at org.antlr.v4.runtime.RuleContext.toStringTree(RuleContext.java:189)
        at Test.DoParse(Test.java:206)
        at Test.ParseFilename(Test.java:135)
        at Test.main(Test.java:107)
```
Surprising, if we as to perform "token.toString()", we get a string with "<no text>" as the text.

APIs should be well designed in preventing crashes like this. The constructor CommonToken(int type) should set basic values for every field, or the parse tree routines should be able to handle a null text field.

**Comment by vityaman** [comment]
@kaby76, is it possible to share on which input data it was died? It would be convenient if I could reproduce this bug exactly in my environment to debug it. Was `CommonToken(int type)` inserted by ANTLR Java Runtime internally or by client code (.java or .g4)?

**Comment by kaby76** [comment]
I don't recall but it was one of the files from the php/examples/ directory. After generating a parser with trgen for Java, build and run the parser with examples/*.php and the `-tree` option. Otherwise run you reproduce it with your own driver that does the same. The grammar base class code was corrected since when this Issue was reported. So make sure to git the specific commit in the link above.
