### ISSUE TITLE
ANTLR Tool version 4.4 used for code generation does not match the current runtime version 4.11.1

### ISSUE THREAD

**Issue by leanderlombardi** [antlr/antlr4#4100]
Version: `ANTLR4 Java`
OS: `Windows 11 Pro 64bit`

ANTLR Tool version 4.4 used for code generation does not match the current runtime version 4.11.1
Exception in thread "main" java.lang.ExceptionInInitializerError
	at main.horizon.main(horizon.java:22)
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:56)
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:48)
	at target.generatedsources.antlr4.horizonLexer.<clinit>(horizonLexer.java:188)
	... 1 more
Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
	... 4 more

Main class code:
```java
package main;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

import target.generatedsources.antlr4.horizonLexer;
import target.generatedsources.antlr4.horizonParser;

public class horizon {
	public static void main(String[] args) throws IOException {
		Scanner scanner = new Scanner(System.in);
		System.out.print("Enter a horizon file: ");
		String fileName = scanner.next();
		File temp = new File(fileName);
		if (temp.exists()) {
			CharStream charStream = CharStreams.fromFileName(fileName);
			horizonLexer lexer = new horizonLexer(charStream);
			CommonTokenStream commonTokenStream = new CommonTokenStream(lexer);
			horizonParser parser = new horizonParser(commonTokenStream);
		} else {
			System.out.println("The file \"" + fileName + "\" doesn't exist!");
			System.exit(1);
		}
	}
}
```

**Comment by leanderlombardi** [comment]
@KvanTTT I only have the eclipse plugin installed,

**Comment by leanderlombardi** [comment]
@KvanTTT How can I regenerate the Lexer? It only gives me the BaseListener, the Listener and the Parser.

**Comment by kaby76** [comment]
> @KvanTTT How can I regenerate the Lexer? It only gives me the BaseListener, the Listener and the Parser.

antlr4 *.g4

https://github.com/antlr/antlr4-tools
