### ISSUE TITLE
Error: Npm package, plain Node: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [antlr/antlr4#4208]
All ANTLR contributors provide implementation, maintenance and support for free.
We therefore kindly ask that before submitting any issue to ANTLR, you please check off these boxes:

- [x ] I have reproduced my issue using the latest version of ANTLR
- [x] I have asked at [stackoverflow](http://stackoverflow.com/questions/tagged/antlr4)
- [x] Responses from the above seem to indicate that my issue could be an ANTLR bug
- [x] I have done a search of the existing issues to make sure I'm not sending in a duplicate
     - Mentioned in: https://github.com/antlr/antlr4/pull/4199

Please include the following information:
 - target information: General language
 - smallest possible grammar and code that reproduces the behavior: No grammar needed
 - description of the expected behavior and actual behavior: Not compiling in plain node project

package.json:
```
{
  "name": "playground",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "tsc",
    "start": "node ./lib/index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^18.15.10",
    "typescript": "^5.0.2"
  },
  "files": [
    "lib/**/*"
  ],
  "dependencies": {
    "antlr4": "^4.12.0"
  }
}
```

src/index.ts
```
const antlr4 = require('antlr4');
const input = "Hello, world!";
const chars = new antlr4.InputStream(input);

export const Greeter = (name: string) => `Hello ${name}`;
```

Reproduce Error:
- "npm install"
- "npm run build"
- "npm run start"

Error:

```
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/nbaumgartner/Documents/GitHub/Playground/node_modules/antlr4/dist/antlr4.node.js
require() of ES modules is not supported.
require() of /Users/nbaumgartner/Documents/GitHub/Playground/node_modules/antlr4/dist/antlr4.node.js from /Users/nbaumgartner/Documents/GitHub/Playground/lib/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename antlr4.node.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/nbaumgartner/Documents/GitHub/Playground/node_modules/antlr4/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/nbaumgartner/Documents/GitHub/Playground/lib/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

Problem mentioned in: https://github.com/antlr/antlr4/pull/4199

**Comment by ericvergnaud** [comment]
Your package must be configured for ESM. Check this: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by NilsBaumgartner1994** [comment]
Configured for esm. Still brings other problems because of esm package
