### ISSUE TITLE
Upgrading from 4.13.0 to 4.13.1 causes rollup/build failure

### ISSUE THREAD

**Issue by kaiyoma** [antlr/antlr4#4415]
Doing a simple upgrade in our project has resulted in this:

```
00:37:47  [commonjs--resolver] Failed to resolve entry for package "antlr4". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by ericvergnaud** [comment]
Probably a duplicate of #4411 ? If so it's already fixed.

**Comment by ncordon** [comment]
Hey @ericvergnaud, could I ask when is the expected date of release for 4.13.2 given 4.13.1 includes this bug in the javascript target? 🙏

**Comment by jonaskello** [comment]
Does antlr 4.13.2 have an expected release date to correct this bug? :-)

**Comment by theolurat** [comment]
Same ? Any fixes?

**Comment by ericvergnaud** [comment]
Just published 4.13.1-patch-1.

**Comment by aovcina** [comment]
The patched version works with a rollup build, thanks @ericvergnaud.

**Comment by theolurat** [comment]
Was working with patch last week but now not working anymore.

Following error :
```bash
23.06 [commonjs--resolver] Failed to resolve entry for package "antlr4". The package may have incorrect main/module/exports specified in its package.json.
23.06 [vite-plugin-sveltekit-compile] Failed to resolve entry for package "antlr4". The package may have incorrect main/module/exports specified in its package.json.
23.06 ✓ built in 20.30s
23.08 error during build:
23.08 Error: Failed to resolve entry for package "antlr4". The package may have incorrect main/module/exports specified in its package.json.
23.08     at packageEntryFailure (file:///app/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
23.08     at resolvePackageEntry (file:///app/node_modules/vite/dist/node/chunks/dep-df561101.js:28688:5)
23.08     at tryNodeResolve (file:///app/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
23.08     at Object.resolveId (file:///app/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
23.08     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
23.08     at async PluginDriver.hookFirstAndGetPlugin (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
23.08     at async resolveId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24117:26)
23.08     at async ModuleLoader.resolveId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24531:15)
23.08     at async Object.resolveId (file:///app/node_modules/vite/dist/node/chunks/dep-df561101.js:7910:10)
23.08     at async PluginDriver.hookFirstAndGetPlugin (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
------
failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 1
```

Any ideas ?

**Comment by ericvergnaud** [comment]
@theolurat Latestversion is 4.13.1-patch-1, released 3 weeks ago, so must be at your end

**Comment by theolurat** [comment]
Yes i'm actually using 4.13.1-patch-1 and got this error.

There is my package.json :

```json
...
 "dependencies": {
		...
		"antlr4": "^4.13.1-patch-1",
		...
 }
...
```

**Comment by andreagentili** [comment]
I couldn't make rollup work not even with the `4.13.1-patch-1` version; I created the minimal repro here: https://github.com/andreagentili/antlr-issue-4.13.1

Anyway what I get when building using rollup is:
```
$ npm install
$ npm run build

> language-parser@1.0.0 build
> rollup -c --bundleConfigAsCjs


src/index.ts → out...
(!) Plugin node-resolve: Could not resolve import "antlr4" in ./src/index.ts using exports defined in ./node_modules/antlr4/package.json.
(!) Plugin node-resolve: Could not resolve import "antlr4" in ./src/grammar/LanguageParser.ts using exports defined in ./node_modules/antlr4/package.json.
(!) Plugin node-resolve: Could not resolve import "antlr4" in ./src/grammar/LanguageVisitor.ts using exports defined in ./node_modules/antlr4/package.json.
(!) Plugin node-resolve: Could not resolve import "antlr4" in ./src/grammar/LanguageLexer.ts using exports defined in ./node_modules/antlr4/package.json.
(!) Plugin node-resolve: Could not resolve import "antlr4" in ./src/grammar/LanguageListener.ts using exports defined in ./node_modules/antlr4/package.json.
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
antlr4 (imported by "src/index.ts", "src/grammar/LanguageParser.ts", "src/grammar/LanguageVisitor.ts", "src/grammar/LanguageLexer.ts" and "src/grammar/LanguageListener.ts")
created out in 409ms
```

Really stuck by now...

**Comment by andreagentili** [comment]
Fixed! It's incredible how many issues can be solved when you just try explaining the problem to others.
In my case you need to configure rollup to use `node-resolve` with `exportConditions: ["node"]` flag, and it works correctly.
