### ISSUE TITLE
help

### ISSUE THREAD

**Issue by appt2** [antlr/antlr4#4447]
hello Plz Help me to decode

```java
public static final String _serializedATN =
            "\u0004\u0000\u0012\u010a\u0006\uffff\uffff\u0006\uffff\uffff\u0006\uffff" +
                    "\uffff\u0002\u0000\u0007\u0000\u0002\u0001\u0007\u0001\u0002\u0002\u0007" +
                    "\u0002\u0002\u0003\u0007\u0003\u0002\u0004\u0007\u0004\u0002\u0005\u0007" +
                    "\u0005\u0002\u0006\u0007\u0006\u0002\u0007\u0007\u0007\u0002\b\u0007\b" +
                    "\u0002\t\u0007\t\u0002\n\u0007\n\u0002\u000b\u0007\u000b\u0002\f\u0007" +
                    "\f\u0002\r\u0007\r\u0002\u000e\u0007\u000e\u0002\u000f\u0007\u000f\u0002" +
                    "\u0010\u0007\u0010\u0002\u0011\u0007\u0011\u0002\u0012\u0007\u0012\u0002" +
                    "\u0013\u0007\u0013\u0002\u0014\u0007\u0014\u0002\u0015\u0007\u0015\u0002" +
                    "\u0016\u0007\u0016\u0002\u0017\u0007\u0017\u0002\u0018\u0007\u0018\u0002" +
                    "\u0019\u0007\u0019\u0002\u001a\u0007\u001a\u0002\u001b\u0007\u001b\u0001" +
                    "\u0000\u0001\u0000\u0001\u0000\u0001\u0000\u0001\u0000\u0001\u0000\u0005" +
                    "\u0000B\b\u0000\n\u0000\f\u0000E\t\u0000\u0001\u0000\u0001\u0000\u0001" +
                    "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001" +
                    "\u0001\u0005\u0001P\b\u0001\n\u0001\f\u0001S\t\u0001\u0001\u0001\u0001" +
                    "\u0001\u0001\u0001\u0001\u0002\u0001\u0002\u0001\u0002\u0001\u0002\u0001" +
                    "\u0002\u0001\u0002\u0001\u0002\u0005\u0002_\b\u0002\n\u0002\f\u0002b\t" +
                    "\u0002\u0001\u0002\u0001\u0002\u0001\u0003\u0001\u0003\u0001\u0003\u0001" +
                    "\u0003\u0001\u0003\u0001\u0003\u0001\u0003\u0001\u0003\u0001\u0003\u0001" +
                    "\u0003\u0001\u0003\u0005\u0003q\b\u0003\n\u0003\f\u0003t\t\u0003\u0001" +
                    "\u0003\u0001\u0003\u0001\u0003\u0001\u0003\u0001\u0004\u0001\u0004\u0001" +
                    "\u0004\u0001\u0004\u0005\u0004~\b\u0004\n\u0004\f\u0004\u0081\t\u0004" +
                    "\u0001\u0004\u0001\u0004\u0001\u0005\u0001\u0005\u0001\u0005\u0001\u0005" +
                    "\u0005\u0005\u0089\b\u0005\n\u0005\f\u0005\u008c\t\u0005\u0001\u0005\u0001" +
                    "\u0005\u0001\u0005\u0001\u0006\u0001\u0006\u0003\u0006\u0093\b\u0006\u0001" +
                    "\u0006\u0004\u0006\u0096\b\u0006\u000b\u0006\f\u0006\u0097\u0001\u0007" +
                    "\u0001\u0007\u0001\u0007\u0001\u0007\u0001\b\u0001\b\u0001\b\u0001\b\u0001" +
                    "\b\u0001\t\u0004\t\u00a4\b\t\u000b\t\f\t\u00a5\u0001\n\u0001\n\u0001\n" +
                    "\u0001\n\u0001\u000b\u0001\u000b\u0001\u000b\u0001\u000b\u0001\u000b\u0001" +
                    "\f\u0001\f\u0001\r\u0001\r\u0001\r\u0001\r\u0001\u000e\u0001\u000e\u0005" +
                    "\u000e\u00b9\b\u000e\n\u000e\f\u000e\u00bc\t\u000e\u0001\u000f\u0001\u000f" +
                    "\u0001\u000f\u0001\u000f\u0001\u0010\u0001\u0010\u0001\u0011\u0001\u0011" +
                    "\u0001\u0012\u0001\u0012\u0001\u0012\u0001\u0012\u0003\u0012\u00ca\b\u0012" +
                    "\u0001\u0013\u0003\u0013\u00cd\b\u0013\u0001\u0014\u0005\u0014\u00d0\b" +
                    "\u0014\n\u0014\f\u0014\u00d3\t\u0014\u0001\u0014\u0001\u0014\u0001\u0014" +
                    "\u0001\u0014\u0001\u0015\u0001\u0015\u0001\u0015\u0001\u0015\u0001\u0015" +
                    "\u0003\u0015\u00de\b\u0015\u0001\u0016\u0004\u0016\u00e1\b\u0016\u000b" +
                    "\u0016\f\u0016\u00e2\u0001\u0016\u0003\u0016\u00e6\b\u0016\u0001\u0017" +
                    "\u0003\u0017\u00e9\b\u0017\u0001\u0018\u0001\u0018\u0004\u0018\u00ed\b" +
                    "\u0018\u000b\u0018\f\u0018\u00ee\u0001\u0019\u0004\u0019\u00f2\b\u0019" +
                    "\u000b\u0019\f\u0019\u00f3\u0001\u0019\u0003\u0019\u00f7\b\u0019\u0001" +
                    "\u001a\u0001\u001a\u0005\u001a\u00fb\b\u001a\n\u001a\f\u001a\u00fe\t\u001a" +
                    "\u0001\u001a\u0001\u001a\u0001\u001b\u0001\u001b\u0005\u001b\u0104\b\u001b" +
                    "\n\u001b\f\u001b\u0107\t\u001b\u0001\u001b\u0001\u001b\u0006CQ`r\u007f" +
                    "\u008a\u0000\u001c\u0003\u0001\u0005\u0002\u0007\u0003\t\u0004\u000b\u0005" +
                    "\r\u0006\u000f\u0007\u0011\b\u0013\t\u0015\n\u0017\u000b\u0019\f\u001b" +
                    "\r\u001d\u000e\u001f\u000f!\u0010#\u0000%\u0000\'\u0000)\u0000+\u0011" +
                    "-\u0012/\u00001\u00003\u00005\u00007\u00009\u0000\u0003\u0000\u0001\u0002" +
                    "\u000b\u0002\u0000\t\t  \u0001\u0000<<\u0003\u0000\t\n\r\r  \u0003\u0000" +
                    "09AFaf\u0001\u000009\u0002\u0000-.__\u0003\u0000\u00b7\u00b7\u0300\u036f" +
                    "\u203f\u2040\b\u0000::AZaz\u2070\u218f\u2c00\u2fef\u3001\u8000\ud7ff\u8000" +
                    "\uf900\u8000\ufdcf\u8000\ufdf0\u8000\ufffd\u0007\u0000##+;==??AZ__az\u0002" +
                    "\u0000\"\"<<\u0002\u0000\'\'<<\u0117\u0000\u0003\u0001\u0000\u0000\u0000" +
                    "\u0000\u0005\u0001\u0000\u0000\u0000\u0000\u0007\u0001\u0000\u0000\u0000" +
                    "\u0000\t\u0001\u0000\u0000\u0000\u0000\u000b\u0001\u0000\u0000\u0000\u0000" +
                    "\r\u0001\u0000\u0000\u0000\u0000\u000f\u0001\u0000\u0000\u0000\u0000\u0011" +
                    "\u0001\u0000\u0000\u0000\u0000\u0013\u0001\u0000\u0000\u0000\u0000\u0015" +
                    "\u0001\u0000\u0000\u0000\u0001\u0017\u0001\u0000\u0000\u0000\u0001\u0019" +
                    "\u0001\u0000\u0000\u0000\u0001\u001b\u0001\u0000\u0000\u0000\u0001\u001d" +
                    "\u0001\u0000\u0000\u0000\u0001\u001f\u0001\u0000\u0000\u0000\u0001!\u0001" +
                    "\u0000\u0000\u0000\u0002+\u0001\u0000\u0000\u0000\u0002-\u0001\u0000\u0000" +
                    "\u0000\u0003;\u0001\u0000\u0000\u0000\u0005J\u0001\u0000\u0000\u0000\u0007" +
                    "W\u0001\u0000\u0000\u0000\te\u0001\u0000\u0000\u0000\u000by\u0001\u0000" +
                    "\u0000\u0000\r\u0084\u0001\u0000\u0000\u0000\u000f\u0095\u0001\u0000\u0000" +
                    "\u0000\u0011\u0099\u0001\u0000\u0000\u0000\u0013\u009d\u0001\u0000\u0000" +
                    "\u0000\u0015\u00a3\u0001\u0000\u0000\u0000\u0017\u00a7\u0001\u0000\u0000" +
                    "\u0000\u0019\u00ab\u0001\u0000\u0000\u0000\u001b\u00b0\u0001\u0000\u0000" +
                    "\u0000\u001d\u00b2\u0001\u0000\u0000\u0000\u001f\u00b6\u0001\u0000\u0000" +
                    "\u0000!\u00bd\u0001\u0000\u0000\u0000#\u00c1\u0001\u0000\u0000\u0000%" +
                    "\u00c3\u0001\u0000\u0000\u0000\'\u00c9\u0001\u0000\u0000\u0000)\u00cc" +
                    "\u0001\u0000\u0000\u0000+\u00d1\u0001\u0000\u0000\u0000-\u00dd\u0001\u0000" +
                    "\u0000\u0000/\u00e0\u0001\u0000\u0000\u00001\u00e8\u0001\u0000\u0000\u0000" +
                    "3\u00ea\u0001\u0000\u0000\u00005\u00f1\u0001\u0000\u0000\u00007\u00f8" +
                    "\u0001\u0000\u0000\u00009\u0101\u0001\u0000\u0000\u0000;<\u0005<\u0000" +
                    "\u0000<=\u0005!\u0000\u0000=>\u0005-\u0000\u0000>?\u0005-\u0000\u0000" +
                    "?C\u0001\u0000\u0000\u0000@B\t\u0000\u0000\u0000A@\u0001\u0000\u0000\u0000" +
                    "BE\u0001\u0000\u0000\u0000CD\u0001\u0000\u0000\u0000CA\u0001\u0000\u0000" +
                    "\u0000DF\u0001\u0000\u0000\u0000EC\u0001\u0000\u0000\u0000FG\u0005-\u0000" +
                    "\u0000GH\u0005-\u0000\u0000HI\u0005>\u0000\u0000I\u0004\u0001\u0000\u0000" +
                    "\u0000JK\u0005<\u0000\u0000KL\u0005!\u0000\u0000LM\u0005[\u0000\u0000" +
                    "MQ\u0001\u0000\u0000\u0000NP\t\u0000\u0000\u0000ON\u0001\u0000\u0000\u0000" +
                    "PS\u0001\u0000\u0000\u0000QR\u0001\u0000\u0000\u0000QO\u0001\u0000\u0000" +
                    "\u0000RT\u0001\u0000\u0000\u0000SQ\u0001\u0000\u0000\u0000TU\u0005]\u0000" +
                    "\u0000UV\u0005>\u0000\u0000V\u0006\u0001\u0000\u0000\u0000WX\u0005<\u0000" +
                    "\u0000XY\u0005?\u0000\u0000YZ\u0005x\u0000\u0000Z[\u0005m\u0000\u0000" +
                    "[\\\u0005l\u0000\u0000\\`\u0001\u0000\u0000\u0000]_\t\u0000\u0000\u0000" +
                    "^]\u0001\u0000\u0000\u0000_b\u0001\u0000\u0000\u0000`a\u0001\u0000\u0000" +
                    "\u0000`^\u0001\u0000\u0000\u0000ac\u0001\u0000\u0000\u0000b`\u0001\u0000" +
                    "\u0000\u0000cd\u0005>\u0000\u0000d\b\u0001\u0000\u0000\u0000ef\u0005<" +
                    "\u0000\u0000fg\u0005!\u0000\u0000gh\u0005[\u0000\u0000hi\u0005C\u0000" +
                    "\u0000ij\u0005D\u0000\u0000jk\u0005A\u0000\u0000kl\u0005T\u0000\u0000" +
                    "lm\u0005A\u0000\u0000mn\u0005[\u0000\u0000nr\u0001\u0000\u0000\u0000o" +
                    "q\t\u0000\u0000\u0000po\u0001\u0000\u0000\u0000qt\u0001\u0000\u0000\u0000" +
                    "rs\u0001\u0000\u0000\u0000rp\u0001\u0000\u0000\u0000su\u0001\u0000\u0000" +
                    "\u0000tr\u0001\u0000\u0000\u0000uv\u0005]\u0000\u0000vw\u0005]\u0000\u0000" +
                    "wx\u0005>\u0000\u0000x\n\u0001\u0000\u0000\u0000yz\u0005<\u0000\u0000" +
                    "z{\u0005!\u0000\u0000{\u007f\u0001\u0000\u0000\u0000|~\t\u0000\u0000\u0000" +
                    "}|\u0001\u0000\u0000\u0000~\u0081\u0001\u0000\u0000\u0000\u007f\u0080" +
                    "\u0001\u0000\u0000\u0000\u007f}\u0001\u0000\u0000\u0000\u0080\u0082\u0001" +
                    "\u0000\u0000\u0000\u0081\u007f\u0001\u0000\u0000\u0000\u0082\u0083\u0005" +
                    ">\u0000\u0000\u0083\f\u0001\u0000\u0000\u0000\u0084\u0085\u0005<\u0000" +
                    "\u0000\u0085\u0086\u0005%\u0000\u0000\u0086\u008a\u0001\u0000\u0000\u0000" +
                    "\u0087\u0089\t\u0000\u0000\u0000\u0088\u0087\u0001\u0000\u0000\u0000\u0089" +
                    "\u008c\u0001\u0000\u0000\u0000\u008a\u008b\u0001\u0000\u0000\u0000\u008a" +
                    "\u0088\u0001\u0000\u0000\u0000\u008b\u008d\u0001\u0000\u0000\u0000\u008c" +
                    "\u008a\u0001\u0000\u0000\u0000\u008d\u008e\u0005%\u0000\u0000\u008e\u008f" +
                    "\u0005>\u0000\u0000\u008f\u000e\u0001\u0000\u0000\u0000\u0090\u0096\u0007" +
                    "\u0000\u0000\u0000\u0091\u0093\u0005\r\u0000\u0000\u0092\u0091\u0001\u0000" +
                    "\u0000\u0000\u0092\u0093\u0001\u0000\u0000\u0000\u0093\u0094\u0001\u0000" +
                    "\u0000\u0000\u0094\u0096\u0005\n\u0000\u0000\u0095\u0090\u0001\u0000\u0000" +
                    "\u0000\u0095\u0092\u0001\u0000\u0000\u0000\u0096\u0097\u0001\u0000\u0000" +
                    "\u0000\u0097\u0095\u0001\u0000\u0000\u0000\u0097\u0098\u0001\u0000\u0000" +
                    "\u0000\u0098\u0010\u0001\u0000\u0000\u0000\u0099\u009a\u0005<\u0000\u0000" +
                    "\u009a\u009b\u0001\u0000\u0000\u0000\u009b\u009c\u0006\u0007\u0000\u0000" +
                    "\u009c\u0012\u0001\u0000\u0000\u0000\u009d\u009e\u0005<\u0000\u0000\u009e" +
                    "\u009f\u0005!\u0000\u0000\u009f\u00a0\u0005-\u0000\u0000\u00a0\u00a1\u0005" +
                    "-\u0000\u0000\u00a1\u0014\u0001\u0000\u0000\u0000\u00a2\u00a4\b\u0001" +
                    "\u0000\u0000\u00a3\u00a2\u0001\u0000\u0000\u0000\u00a4\u00a5\u0001\u0000" +
                    "\u0000\u0000\u00a5\u00a3\u0001\u0000\u0000\u0000\u00a5\u00a6\u0001\u0000" +
                    "\u0000\u0000\u00a6\u0016\u0001\u0000\u0000\u0000\u00a7\u00a8\u0005>\u0000" +
                    "\u0000\u00a8\u00a9\u0001\u0000\u0000\u0000\u00a9\u00aa\u0006\n\u0001\u0000" +
                    "\u00aa\u0018\u0001\u0000\u0000\u0000\u00ab\u00ac\u0005/\u0000\u0000\u00ac" +
                    "\u00ad\u0005>\u0000\u0000\u00ad\u00ae\u0001\u0000\u0000\u0000\u00ae\u00af" +
                    "\u0006\u000b\u0001\u0000\u00af\u001a\u0001\u0000\u0000\u0000\u00b0\u00b1" +
                    "\u0005/\u0000\u0000\u00b1\u001c\u0001\u0000\u0000\u0000\u00b2\u00b3\u0005" +
                    "=\u0000\u0000\u00b3\u00b4\u0001\u0000\u0000\u0000\u00b4\u00b5\u0006\r" +
                    "\u0002\u0000\u00b5\u001e\u0001\u0000\u0000\u0000\u00b6\u00ba\u0003)\u0013" +
                    "\u0000\u00b7\u00b9\u0003\'\u0012\u0000\u00b8\u00b7\u0001\u0000\u0000\u0000" +
                    "\u00b9\u00bc\u0001\u0000\u0000\u0000\u00ba\u00b8\u0001\u0000\u0000\u0000" +
                    "\u00ba\u00bb\u0001\u0000\u0000\u0000\u00bb \u0001\u0000\u0000\u0000\u00bc" +
                    "\u00ba\u0001\u0000\u0000\u0000\u00bd\u00be\u0007\u0002\u0000\u0000\u00be" +
                    "\u00bf\u0001\u0000\u0000\u0000\u00bf\u00c0\u0006\u000f\u0003\u0000\u00c0" +
                    "\"\u0001\u0000\u0000\u0000\u00c1\u00c2\u0007\u0003\u0000\u0000\u00c2$" +
                    "\u0001\u0000\u0000\u0000\u00c3\u00c4\u0007\u0004\u0000\u0000\u00c4&\u0001" +
                    "\u0000\u0000\u0000\u00c5\u00ca\u0003)\u0013\u0000\u00c6\u00ca\u0007\u0005" +
                    "\u0000\u0000\u00c7\u00ca\u0003%\u0011\u0000\u00c8\u00ca\u0007\u0006\u0000" +
                    "\u0000\u00c9\u00c5\u0001\u0000\u0000\u0000\u00c9\u00c6\u0001\u0000\u0000" +
                    "\u0000\u00c9\u00c7\u0001\u0000\u0000\u0000\u00c9\u00c8\u0001\u0000\u0000" +
                    "\u0000\u00ca(\u0001\u0000\u0000\u0000\u00cb\u00cd\u0007\u0007\u0000\u0000" +
                    "\u00cc\u00cb\u0001\u0000\u0000\u0000\u00cd*\u0001\u0000\u0000\u0000\u00ce" +
                    "\u00d0\u0005 \u0000\u0000\u00cf\u00ce\u0001\u0000\u0000\u0000\u00d0\u00d3" +
                    "\u0001\u0000\u0000\u0000\u00d1\u00cf\u0001\u0000\u0000\u0000\u00d1\u00d2" +
                    "\u0001\u0000\u0000\u0000\u00d2\u00d4\u0001\u0000\u0000\u0000\u00d3\u00d1" +
                    "\u0001\u0000\u0000\u0000\u00d4\u00d5\u0003-\u0015\u0000\u00d5\u00d6\u0001" +
                    "\u0000\u0000\u0000\u00d6\u00d7\u0006\u0014\u0001\u0000\u00d7,\u0001\u0000" +
                    "\u0000\u0000\u00d8\u00de\u00037\u001a\u0000\u00d9\u00de\u00039\u001b\u0000" +
                    "\u00da\u00de\u0003/\u0016\u0000\u00db\u00de\u00033\u0018\u0000\u00dc\u00de" +
                    "\u00035\u0019\u0000\u00dd\u00d8\u0001\u0000\u0000\u0000\u00dd\u00d9\u0001" +
                    "\u0000\u0000\u0000\u00dd\u00da\u0001\u0000\u0000\u0000\u00dd\u00db\u0001" +
                    "\u0000\u0000\u0000\u00dd\u00dc\u0001\u0000\u0000\u0000\u00de.\u0001\u0000" +
                    "\u0000\u0000\u00df\u00e1\u00031\u0017\u0000\u00e0\u00df\u0001\u0000\u0000" +
                    "\u0000\u00e1\u00e2\u0001\u0000\u0000\u0000\u00e2\u00e0\u0001\u0000\u0000" +
                    "\u0000\u00e2\u00e3\u0001\u0000\u0000\u0000\u00e3\u00e5\u0001\u0000\u0000" +
                    "\u0000\u00e4\u00e6\u0005 \u0000\u0000\u00e5\u00e4\u0001\u0000\u0000\u0000" +
                    "\u00e5\u00e6\u0001\u0000\u0000\u0000\u00e60\u0001\u0000\u0000\u0000\u00e7" +
                    "\u00e9\u0007\b\u0000\u0000\u00e8\u00e7\u0001\u0000\u0000\u0000\u00e92" +
                    "\u0001\u0000\u0000\u0000\u00ea\u00ec\u0005#\u0000\u0000\u00eb\u00ed\u0007" +
                    "\u0003\u0000\u0000\u00ec\u00eb\u0001\u0000\u0000\u0000\u00ed\u00ee\u0001" +
                    "\u0000\u0000\u0000\u00ee\u00ec\u0001\u0000\u0000\u0000\u00ee\u00ef\u0001" +
                    "\u0000\u0000\u0000\u00ef4\u0001\u0000\u0000\u0000\u00f0\u00f2\u0007\u0004" +
                    "\u0000\u0000\u00f1\u00f0\u0001\u0000\u0000\u0000\u00f2\u00f3\u0001\u0000" +
                    "\u0000\u0000\u00f3\u00f1\u0001\u0000\u0000\u0000\u00f3\u00f4\u0001\u0000" +
                    "\u0000\u0000\u00f4\u00f6\u0001\u0000\u0000\u0000\u00f5\u00f7\u0005%\u0000" +
                    "\u0000\u00f6\u00f5\u0001\u0000\u0000\u0000\u00f6\u00f7\u0001\u0000\u0000" +
                    "\u0000\u00f76\u0001\u0000\u0000\u0000\u00f8\u00fc\u0005\"\u0000\u0000" +
                    "\u00f9\u00fb\b\t\u0000\u0000\u00fa\u00f9\u0001\u0000\u0000\u0000\u00fb" +
                    "\u00fe\u0001\u0000\u0000\u0000\u00fc\u00fa\u0001\u0000\u0000\u0000\u00fc" +
                    "\u00fd\u0001\u0000\u0000\u0000\u00fd\u00ff\u0001\u0000\u0000\u0000\u00fe" +
                    "\u00fc\u0001\u0000\u0000\u0000\u00ff\u0100\u0005\"\u0000\u0000\u01008" +
                    "\u0001\u0000\u0000\u0000\u0101\u0105\u0005\'\u0000\u0000\u0102\u0104\b" +
                    "\n\u0000\u0000\u0103\u0102\u0001\u0000\u0000\u0000\u0104\u0107\u0001\u0000" +
                    "\u0000\u0000\u0105\u0103\u0001\u0000\u0000\u0000\u0105\u0106\u0001\u0000" +
                    "\u0000\u0000\u0106\u0108\u0001\u0000\u0000\u0000\u0107\u0105\u0001\u0000" +
                    "\u0000\u0000\u0108\u0109\u0005\'\u0000\u0000\u0109:\u0001\u0000\u0000" +
                    "\u0000\u001a\u0000\u0001\u0002CQ`r\u007f\u008a\u0092\u0095\u0097\u00a5" +
                    "\u00ba\u00c9\u00cc\u00d1\u00dd\u00e2\u00e5\u00e8\u00ee\u00f3\u00f6\u00fc" +
                    "\u0105\u0004\u0005\u0001\u0000\u0004\u0000\u0000\u0005\u0002\u0000\u0000" +
                    "\u0001\u0000";

```

**Comment by ericvergnaud** [comment]
The above is decoded by the ATNDeserializer. Why do you want to decode it yourself ?

**Comment by appt2** [comment]
> The above is decoded by the ATNDeserializer. Why do you want to decode it yourself ?

Because this code is a part of the developed html language, in the Sora editor code, this code has a problem that it does not color the style tag and it makes my program lifeless.

**Comment by ericvergnaud** [comment]
It's unlikely that you'll be able to fix a styling issue by deserializing this code. Can you tell us more about the styling issue ? Is the Sora editor code unable to style the above Java code ? Or is it about the Html code parsed using the above serialized ATN ?

**Comment by appt2** [comment]
> It's unlikely that you'll be able to fix a styling issue by deserializing this code. Can you tell us more about the styling issue ? Is the Sora editor code unable to style the above Java code ? Or is it about the Html code parsed using the above serialized ATN ?

Yes, with the code above, you can see the generated html code here

https://github.com/Rosemoe/sora-editor/blob/past-0.8.x/language-html/src/main/java/io/github/rosemoe/sora/langs/html/HTMLLexer.java

**Comment by kaby76** [comment]
> Yes, with the code above, you can see the generated html code here
> 
> https://github.com/Rosemoe/sora-editor/blob/past-0.8.x/language-html/src/main/java/io/github/rosemoe/sora/langs/html/HTMLLexer.java

There's no `HTML*.g` or `HTML*.g4` in that branch of the repo. It sounds like he wants to reverse engineer the ATN code, which was generated from v4.9.1 of the tool, to derive the .g4, then update the grammar with new syntax, and create a new editor that colorizes the new tokens. The other lexers have corresponding .g4's in the repo, CSS3Lexer.java/css3.g4, PythonLexer.java/PythonLexer.g4, XMLLexer.java/XMLLexer.g4.

**Comment by appt2** [comment]
> > Yes, with the code above, you can see the generated html code here
> > https://github.com/Rosemoe/sora-editor/blob/past-0.8.x/language-html/src/main/java/io/github/rosemoe/sora/langs/html/HTMLLexer.java
> 
> There's no `HTML*.g` or `HTML*.g4` in that branch of the repo. It sounds like he wants to reverse engineer the ATN code, which was generated from v4.9.1 of the tool, to derive the .g4, then update the grammar with new syntax, and create a new editor that colorizes the new tokens. The other lexers have corresponding .g4's in the repo, CSS3Lexer.java/css3.g4, PythonLexer.java/PythonLexer.g4, XMLLexer.java/XMLLexer.g4.

That is exactly what I want to update the grammar

**Comment by kaby76** [comment]
May I make a suggestion? Instead of trying to reverse engineer the code to derive the grammar, I suggest you just assume that the grammar came from [grammars-v4/html](https://github.com/antlr/grammars-v4/tree/master/html). Then, under that assumption, determine what version of the grammar best matches your code.

You can then write a simple bash script that loops through all commits of HTMLLexer.g4 to perform a diff between the generated code from grammars-v4 and what exists in the https://github.com/Rosemoe/sora-editor repo. To be exact, you must use version 4.9.1 of the Antlr Tool. Fortunately, there's a beautiful Python script that runs the tool with that version [here](https://github.com/antlr/antlr4-tools).

Besides the fact that the author never bothered to check in the HTMLLexer.g4 grammar to begin with, what makes this problem difficult is the fact that the author decided to ***hand-edit all the generated code***. I cannot tell how completely wrong this is. You never hand-edit generated code: it's unreproducible.

Fortunately, the author could only apply so much BS in reformatting the code. In particular, the `_serializedATN` table seems to be relatively unchanged. I isolated the table using sed's, fixed the BS formatting, and found that [this version of HTMLLexer.g4](https://github.com/antlr/grammars-v4/blob/e2cb6f428bf0fdef7833acf4414f2c2730362b83/html/HTMLLexer.g4) is the one you want. You may want to see what was changed in the three years since that version.

This was the script that I wrote to find the minimum diff.

```
#
temp1=`mktemp`
temp2=`mktemp`
echo $temp1
echo $temp2
git checkout master
commits=`git log HTMLLexer.g4 | grep '^commit' | awk '{print $2}'`
echo $commits

for c in $commits
do
	echo $c
	git checkout $c
	antlr4 -v 4.9.1 HTMLLexer.g4
	cat HTMLLexer.java > $temp1
	while true
	do
		cat $temp1 | sed 's/\t/ /g' | sed 's/[ ][ ]/ /g' | sed 's/ = /=/g' | sed 's/["] +$/"+/' > fu
		diff -q $temp1 fu
		if [ $? -eq 0 ]
		then
			break
		fi
		cat fu > $temp1
	done
	cat $temp1 | sed '1,/^ public static final String _serializedATN =$/d' > fu
	mv fu $temp1
	cat $temp1 | sed '/^ public static final ATN _ATN =$/,$d' > fu
	mv fu $temp1

	cat 'c:\msys64\home\Kenne\sora-editor\language-html\src\main\java\io\github\rosemoe\sora\langs\html\HTMLLexer.java' > $temp2
	while true
	do
		cat $temp2 | sed 's/\t/ /g' | sed 's/[ ][ ]/ /g' | sed 's/ = /=/g' | sed 's/["] +$/"+/' > fu
		diff -q $temp2 fu
		if [ $? -eq 0 ]
		then
			break
		fi
		cat fu > $temp2
	done
	cat $temp2 | sed '1,/^ public static final String _serializedATN =$/d' > fu
	mv fu $temp2
	cat $temp2 | sed '/^ public static final ATN _ATN =$/,$d' > fu
	mv fu $temp2
	diff $temp1 $temp2 | wc
done

rm -f $temp1 $temp2

```

**Comment by appt2** [comment]
> May I make a suggestion? Instead of trying to reverse engineer the code to derive the grammar, I suggest you just assume that the grammar came from [grammars-v4/html](https://github.com/antlr/grammars-v4/tree/master/html). Then, under that assumption, determine what version of the grammar best matches your code.
> 
> You can then write a simple bash script that loops through all commits of HTMLLexer.g4 to perform a diff between the generated code from grammars-v4 and what exists in the https://github.com/Rosemoe/sora-editor repo. To be exact, you must use version 4.9.1 of the Antlr Tool. Fortunately, there's a beautiful Python script that runs the tool with that version [here](https://github.com/antlr/antlr4-tools).
> 
> Besides the fact that the author never bothered to check in the HTMLLexer.g4 grammar to begin with, what makes this problem difficult is that the generated code is _**hand-edited**_. I cannot tell how wrong this is. You will need to figure out what was changed.
> 
> Fortunately, the reformatting doesn't affect all the code. In particular, the `_serializedATN` table seems to be relatively unchanged. I isolated the table using sed's, fixed minor formatting changes, and found that [this version of HTMLLexer.g4](https://github.com/antlr/grammars-v4/blob/e2cb6f428bf0fdef7833acf4414f2c2730362b83/html/HTMLLexer.g4) is the one you want. You may want to see what was changed in the three years since that version.
> 
> This was the script that I wrote to find the minimum diff--_**which is an exact match with the above linked HTMLLexer.g4**_.
> 
> ```
> #
> temp1=`mktemp`
> temp2=`mktemp`
> echo $temp1
> echo $temp2
> git checkout master
> commits=`git log HTMLLexer.g4 | grep '^commit' | awk '{print $2}'`
> echo $commits
> 
> for c in $commits
> do
> 	echo $c
> 	git checkout $c
> 	antlr4 -v 4.9.1 HTMLLexer.g4
> 	cat HTMLLexer.java > $temp1
> 	while true
> 	do
> 		cat $temp1 | sed 's/\t/ /g' | sed 's/[ ][ ]/ /g' | sed 's/ = /=/g' | sed 's/["] +$/"+/' > fu
> 		diff -q $temp1 fu
> 		if [ $? -eq 0 ]
> 		then
> 			break
> 		fi
> 		cat fu > $temp1
> 	done
> 	cat $temp1 | sed '1,/^ public static final String _serializedATN =$/d' > fu
> 	mv fu $temp1
> 	cat $temp1 | sed '/^ public static final ATN _ATN =$/,$d' > fu
> 	mv fu $temp1
> 
> 	cat 'c:\msys64\home\Kenne\sora-editor\language-html\src\main\java\io\github\rosemoe\sora\langs\html\HTMLLexer.java' > $temp2
> 	while true
> 	do
> 		cat $temp2 | sed 's/\t/ /g' | sed 's/[ ][ ]/ /g' | sed 's/ = /=/g' | sed 's/["] +$/"+/' > fu
> 		diff -q $temp2 fu
> 		if [ $? -eq 0 ]
> 		then
> 			break
> 		fi
> 		cat fu > $temp2
> 	done
> 	cat $temp2 | sed '1,/^ public static final String _serializedATN =$/d' > fu
> 	mv fu $temp2
> 	cat $temp2 | sed '/^ public static final ATN _ATN =$/,$d' > fu
> 	mv fu $temp2
> 	diff $temp1 $temp2 | wc
> done
> 
> rm -f $temp1 $temp2
> ```

Unfortunately, I tested it, but nothing happened. The tag style and script are colorless again

**Comment by ericvergnaud** [comment]
the generated lexer and parser do NOT perform any colorization. You need to look at the code that uses them - that's not antlr4 code.

**Comment by appt2** [comment]
> the generated lexer and parser do NOT perform any colorization. You need to look at the code that uses them - that's not antlr4 code. It seems that's done by HTMLAnalyzer.java. It's not handling the SCRIPT_OPEN and STYLE_OPEN tokens...

Well, I added these, only the open style and script tags are colored, but not the closed tag

**Comment by ericvergnaud** [comment]
How about TAG_CLOSE ?

**Comment by appt2** [comment]
> How about TAG_CLOSE ?

Already implemented, try to implement the project in Android Studio, you will understand the error yourself, this is a suggestion

**Comment by ericvergnaud** [comment]
Hey, the error is in your code, not in ANTLR, and none of us is getting paid to help you. If you check the html grammar, you'll find that you need to cater for SCRIPT_BODY and STYLE_BODY. The closing tag is at the end of these tokens.

**Comment by appt2** [comment]
Display Metrics:
- Width: 1080px
- Height: 2176px
- Density: 440dpi
- Scaled Density: 2.75

Build Information:
- Board: moonstone
- Brand: POCO
- Device ID: TKQ1.221114.001
- Display: TKQ1.221114.001 test-keys
- Manufacturer: Xiaomi
- Model: 22111317PG
- Product: moonstone_p_global
- Serial Number: unknown

Telephony Information:
- Sim Operator Name: Irancell
- Phone Type: GSM
SDK: 33
Android: 13
Model: V14.0.5.0.TMPMIXM
App version: 1.5.6

java.lang.ExceptionInInitializerError
 at io.github.rosemoe.sora.langs.python.PythonCodeAnalyzer.analyze(PythonCodeAnalyzer.java:24)
 at io.github.rosemoe.sora.text.TextAnalyzer$AnalyzeThread.run(TextAnalyzer.java:205)
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
 at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:56)
 at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:48)
 at io.github.rosemoe.sora.langs.python.PythonLexer.<clinit>(PythonLexer.java:655)
 ... 2 more
Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
 ... 5 more


Thu Oct 26 09:25:42 GMT+03:30 2023



I have updated your library to the latest version, as I said, I use html, Python and .... The link to the sora library is above, but the program crashes.

**Comment by kaby76** [comment]
You have a tool/runtime version skew. The version of Antlr tool used to generate the lexer and the runtime that the program references have to be the same. You will need to get in a debugger and break at the exception then see what is what. I thought that the program needs to generate using 4.9.1 of the tool.
