### ISSUE TITLE
g4 file Compile Error

### ISSUE THREAD

**Issue by appt2** [antlr/antlr4#4472]
Hello, I tried to compile a grammar file with the Tool class, but I get this error, my Java code is below the error.

```bash
Display Metrics:
- Width: 1080px
- Height: 2176px
- Density: 440dpi
- Scaled Density: 2.75

Build Information:
- Board: moonstone
- Brand: POCO
- Device ID: TKQ1.221114.001
- Display: TKQ1.221114.001 test-keys
- Manufacturer: Xiaomi
- Model: 22111317PG
- Product: moonstone_p_global
- Serial Number: unknown

Telephony Information:
- Sim Operator Name: Irancell
- Phone Type: GSM
SDK: 33
Android: 13
Model: V14.0.5.0.TMPMIXM
App version: 1.5.6

java.lang.VerifyError: Verifier rejected class org.antlr.v4.tool.ErrorManager: void org.antlr.v4.tool.ErrorManager.internalError(java.lang.String, java.lang.Throwable) failed to verify: void org.antlr.v4.tool.ErrorManager.internalError(java.lang.String, java.lang.Throwable): [0x4] invalid argument count (3) exceeds outsSize (1) (declaration of 'org.antlr.v4.tool.ErrorManager' appears in /data/app/~~TBQ6h-98ddZfU79vAH4fsA==/Ninja.coder.Ghostemane.code--d52qp_yMsFTNuv730KrGw==/base.apk!classes112.dex)
	at org.antlr.v4.Tool.<init>(Tool.java:187)
	at Ninja.coder.Ghostemane.code.G4Compiler.compile(G4Compiler.java:16)
	at Ninja.coder.Ghostemane.code.CodeeditorActivity$40.onClick(CodeeditorActivity.java:3489)
	at android.view.View.performClick(View.java:7556)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
	at android.view.View.performClickInternal(View.java:7533)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29663)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)


Wed Nov 22 21:04:49 GMT+03:30 2023
```

my java code

```java

package Ninja.coder.Ghostemane.code;

import Ninja.coder.Ghostemane.code.FileUtil;
import android.widget.TextView;
import java.io.File;
import org.antlr.v4.Tool;

public class G4Compiler {
    //This is a fake text view, ignore it
  public static void compile(String path, String outpath, String packages, TextView log) {
    // TODO: path = set File g4
    // TODO: pathfile = set File dir to make files
    // TODO: set packages like in package Ninja.coder.Ghostemane.code.lang....
    String[] helper = {
      path, "-o", outpath, "-package", packages
    };
    Tool tool = new Tool(helper);
    tool.processGrammarsOnCommandLine();
  }

  public static void compile(String path, String outpath, String packages) {
    compile(path, outpath, packages);
  }

  public static void compile(String path, String outpath) {
    compile(path, outpath, "Ninja.coder.Ghostemane.code");
  }

  public void compile(String path) {
    String filename = new File(path).getName();
    int extensionIndex = filename.lastIndexOf(".");
    if (extensionIndex > 0) {
      filename = filename.substring(0, extensionIndex);
    }
    if (!FileUtil.isDirectory("/storage/emulated/0/GhostWebIDE/g4Compile")) {
      FileUtil.makeDir("/storage/emulated/0/GhostWebIDE/g4Compile");
    } else {
      if (FileUtil.isDirectory("/storage/emulated/0/GhostWebIDE/g4Compile"))
        compile(path, "/storage/emulated/0/GhostWebIDE/g4Compile/" + filename);
    }
  }
}
```

**Comment by appt2** [comment]
@parrt plz help me!

**Comment by parrt** [comment]
Sorry but I can't really help you on that. It looks like some kind of android error message.

**Comment by parrt** [comment]
(dex files)

**Comment by appt2** [comment]
> Sorry but I can't really help you on that. It looks like some kind of android error message.

Can you give me a sample code to translate g4 files to Java?

**Comment by appt2** [comment]
Well I wrote a new code

```java

package Ninja.coder.Ghostemane.code;

import android.util.Log;
import java.io.File;
import org.antlr.v4.Tool;
import org.antlr.v4.tool.ANTLRMessage;
import org.antlr.v4.tool.ANTLRToolListener;

public class G4Compiler {
  public static void compile(String path, String outpath, String packages) {
    // TODO: path = set File g4
    // TODO: pathfile = set File dir to make files
    // TODO: set packages like in package Ninja.coder.Ghostemane.code.lang....
    Tool tool = new Tool();
    tool.outputDirectory = outpath;
    tool.genPackage = packages;
    tool.inputDirectory = new File(path);

    tool.addListener(
        new ANTLRToolListener() {

          @Override
          public void info(String info) {
            Log.e("info", info);
          }

          @Override
          public void error(ANTLRMessage errormsg) {
            Log.e("Error", errormsg.toString());
          }

          @Override
          public void warning(ANTLRMessage warmsg) {
            Log.e("warning", warmsg.toString());
          }
        });
  }
}

```

This results in an error

```bash


Display Metrics:
- Width: 1080px
- Height: 2176px
- Density: 440dpi
- Scaled Density: 2.75

Build Information:
- Board: moonstone
- Brand: POCO
- Device ID: TKQ1.221114.001
- Display: TKQ1.221114.001 test-keys
- Manufacturer: Xiaomi
- Model: 22111317PG
- Product: moonstone_p_global
- Serial Number: unknown

Telephony Information:
- Sim Operator Name: Irancell
- Phone Type: GSM
SDK: 33
Android: 13
Model: V14.0.6.0.TMPMIXM
App version: 1.5.6

java.lang.VerifyError: Verifier rejected class org.antlr.v4.tool.ErrorManager: void org.antlr.v4.tool.ErrorManager.internalError(java.lang.String, java.lang.Throwable) failed to verify: void org.antlr.v4.tool.ErrorManager.internalError(java.lang.String, java.lang.Throwable): [0x4] invalid argument count (3) exceeds outsSize (1) (declaration of 'org.antlr.v4.tool.ErrorManager' appears in /data/app/~~z8FnvBb2JW-8m0x1yRdy6A==/Ninja.coder.Ghostemane.code-GGLaQzT6xR2wSrDozNfVwA==/base.apk!classes112.dex)
	at org.antlr.v4.Tool.<init>(Tool.java:187)
	at org.antlr.v4.Tool.<init>(Tool.java:183)
	at Ninja.coder.Ghostemane.code.G4Compiler.compile(G4Compiler.java:16)
	at Ninja.coder.Ghostemane.code.CodeeditorActivity$40.onClick(CodeeditorActivity.java:3489)
	at android.view.View.performClick(View.java:7556)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
	at android.view.View.performClickInternal(View.java:7533)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29663)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)


Thu Nov 23 02:51:33 GMT+03:30 2023

```
