### ISSUE TITLE
Antlr4 failing to reach out to Maven repository

### ISSUE THREAD

**Issue by Cazra** [antlr/antlr4#4703]
This morning, I've been having trouble trying to do anything at all with Antlr4. I can't use it to build any of my grammars, and not even `antlr4 --help` works.

I get the following error output:
```
Traceback (most recent call last):
  File "/usr/local/bin/antlr4", line 8, in <module>
    sys.exit(tool())
  File "/usr/local/lib/python3.10/dist-packages/antlr4_tool_runner.py", line 141, in tool
    run_cli('org.antlr.v4.Tool')
  File "/usr/local/lib/python3.10/dist-packages/antlr4_tool_runner.py", line 132, in run_cli
    args, version = process_args()
  File "/usr/local/lib/python3.10/dist-packages/antlr4_tool_runner.py", line 126, in process_args
    args.version or os.environ.get("ANTLR4_TOOLS_ANTLR_VERSION") or latest_version()
  File "/usr/local/lib/python3.10/dist-packages/antlr4_tool_runner.py", line 27, in latest_version
    with urlopen(f"https://search.maven.org/solrsearch/select?q=a:antlr4-master+g:org.antlr", timeout=10) as response:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
```

It appears to be timing out when it reaches out to its Maven repository.

**Comment by kaby76** [comment]
`https://search.maven.org/solrsearch/select?q=a:antlr4-master+g:org.antlr`. I mentioned this here. https://github.com/antlr/antlr4/issues/4698#issuecomment-2376841225. The change, [which should be in the antlr4-tools repo](https://github.com/antlr/antlr4-tools/blob/10a090aab6ec70217d1d8aa0c2f16c9f1e425861/antlr4_tool_runner.py#L24-L44), looks instead to `https://repo1.maven.org/maven2/org/antlr/antlr4/`, avoiding `search.maven.org` entirely. It's not robust, frequently--if not more than not--down.

**Comment by moogman** [comment]
antlr4 python is unusable again because there's an outage with https://status.maven.org/
This should be a soft failure with antlr4, warning instead of erroring out.
--help and --version should work even if maven is down, and we also should have a --skip-version-check cmdline option.

**Comment by moogman** [comment]
Duplicate of https://github.com/antlr/antlr4-tools/issues/18 as this is a bug of antlr4-tools rather than antlr4 itself

**Comment by kaby76** [comment]
Yes, the current workaround is to always use the `-v` "option." But, you may want to use `-v` for another reason.

In [grammars-v4](https://github.com/antlr/grammars-v4), we always use the `-v` "option" because the tool and runtime versions must be kept in sync. So, while a new version of the tool may be released, the runtimes are released in a completely different timetable, sometimes up to a month after the release of the tool.

**Comment by moogman** [comment]
Cross referencing to https://github.com/antlr/antlr4-tools/issues/18#issuecomment-2393700562
There's a fix that's not made it to a pip release yet, that errors cleanly when there's a timeout and automatically uses any current JRE as a fallback option.

In the meantime, you can add that manually in your envs:
```
.env/lib/python3.12/site-packages/antlr4_tool_runner.py:35
-    except (error.URLError, error.HTTPError) as e:
+    except (error.URLError, error.HTTPError, TimeoutError) as e:
```
