### ISSUE TITLE
null ptr exception for arg on expr rule

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#556]
From grammar

```
        String grammar =
                "grammar T;\n" +
                "s : e ';' ;\n" +
                "e : e '*' e\n" +
                "  | e '+' e[4]\n" +
                "  | e '.' ID\n" +
                "  | '-' e\n" +
                "  | ID\n" +
                "  ;\n" +
                "ID : [a-z]+ ;\n";
```

we get

```
java.lang.NullPointerException
	at org.antlr.v4.automata.ParserATNFactory.elemList(ParserATNFactory.java:492)
	at org.antlr.v4.automata.ParserATNFactory.alt(ParserATNFactory.java:473)
	at org.antlr.v4.parse.ATNBuilder.alternative(ATNBuilder.java:568)
	at org.antlr.v4.parse.ATNBuilder.block(ATNBuilder.java:401)
	at org.antlr.v4.parse.ATNBuilder.subrule(ATNBuilder.java:1172)
	at org.antlr.v4.parse.ATNBuilder.element(ATNBuilder.java:888)
	at org.antlr.v4.parse.ATNBuilder.alternative(ATNBuilder.java:551)
	at org.antlr.v4.parse.ATNBuilder.ruleBlock(ATNBuilder.java:290)
	at org.antlr.v4.automata.ParserATNFactory._createATN(ParserATNFactory.java:184)
	at org.antlr.v4.automata.ParserATNFactory.createATN(ParserATNFactory.java:134)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:405)
	at org.antlr.v4.Tool.process(Tool.java:384)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:343)
	at org.antlr.v4.test.BaseTest.antlr(BaseTest.java:438)
	at org.antlr.v4.test.BaseTest.testErrors(BaseTest.java:747)
	at org.antlr.v4.test.TestLexerPositionDirective.testInvalidCharAtStart(TestLexerPositionDirective.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by KvanTTT** [comment]
Not reproduced. I get the following error:
```error(80): T.g4:4:10: rule e has no defined parameters```

If I removed ```[4]``` parameter, process executes without errors.

**Comment by parrt** [comment]
ok, thanks. closing.
