### ISSUE TITLE
lexer grammar, import names very particular

### ISSUE THREAD

**Issue by james-q-arnold** [antlr/antlr4#560]
I split a grammer into a parser and a lexer.  It appears the runtime package is very particular about the selected names.  I had a lexer named 'SomeLex' and a parser 'SomeParser'.

```
$ grun SomeParser r
Exception in thread "main" java.lang.ClassCastException: class SomeParser
    at java.lang.Class.asSubclass(Class.java:3126)
    at org.antlr.v4.runtime.misc.TestRig.process(TestRig.java:159)
    at org.antlr.v4.runtime.misc.TestRig.main(TestRig.java:143)
$ grun Some r
Can't load Some as lexer or parser
```

Changing the lexer to 'SomeLexer' fixed the problem.  By the way, I was using antlr4.  The parser used tokenVocab to import the lexer.  I would attach the files, but I don't see a way to do that in the github error report.  The files were trivial: one rule (r) in the parser, three simple token rules in the lexer.

**Comment by mikecargal** [comment]
This one seems to get me every time I'm away from running TestRig for a while.  I end up typing `grun BlahParser someRule < infile` (`grun Blah someRule < infile`) and get this error message.  Then I have to go pull up the file and realize that I should have left off the "Parser" part.  For split grammars, it's "non-obvious" at best.  Consider this another vote for either trying for the input name as typed (without appending "Parser" or "Lexer", or at least a better error message.

I might even take a crack at it if everyone is open to the idea.
