### ISSUE TITLE
exception when importing grammar

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4#670]
4.3 seems to do same thing as 4.4. 4.2.2 worked.

```
~/antlr/code/grammars-v4/java $ cp Java.g4 /tmp
~/antlr/code/grammars-v4/java $ pushd /tmp
/tmp ~/antlr/code/grammars-v4/java
/tmp $ cat > NewJava.g4
grammar NewJava;
import Java;
/tmp $ a4 NewJava.g4 
Exception in thread "main" java.util.NoSuchElementException: token index 1851 out of range 0..11
	at org.antlr.runtime.BufferedTokenStream.get(BufferedTokenStream.java:154)
	at org.antlr.v4.parse.GrammarToken.getLine(GrammarToken.java:57)
	at org.antlr.runtime.tree.CommonTreeNodeStream.hasPositionInformation(CommonTreeNodeStream.java:208)
	at org.antlr.runtime.tree.CommonTreeNodeStream.remove(CommonTreeNodeStream.java:116)
	at org.antlr.runtime.misc.LookaheadStream.consume(LookaheadStream.java:97)
	at org.antlr.runtime.tree.TreeParser.matchAny(TreeParser.java:118)
	at org.antlr.v4.parse.BlockSetTransformer.topdown(BlockSetTransformer.java:328)
	at org.antlr.v4.parse.BlockSetTransformer.topdown(BlockSetTransformer.java:24)
	at org.antlr.runtime.tree.TreeRewriter$2.rule(TreeRewriter.java:111)
	at org.antlr.runtime.tree.TreeRewriter.applyOnce(TreeRewriter.java:61)
	at org.antlr.runtime.tree.TreeRewriter$1.pre(TreeRewriter.java:93)
	at org.antlr.runtime.tree.TreeVisitor.visit(TreeVisitor.java:56)
	at org.antlr.runtime.tree.TreeRewriter.downup(TreeRewriter.java:97)
	at org.antlr.runtime.tree.TreeRewriter.downup(TreeRewriter.java:86)
	at org.antlr.v4.tool.GrammarTransformPipeline.reduceBlocksToSets(GrammarTransformPipeline.java:89)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRule(LeftRecursiveRuleTransformer.java:149)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRules(LeftRecursiveRuleTransformer.java:96)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:94)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
	at org.antlr.v4.Tool.process(Tool.java:387)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:346)
	at org.antlr.v4.Tool.main(Tool.java:193)
```

**Comment by EpsilonPrime** [comment]
I still see this behavior in 4.5 rc1.

**Comment by parrt** [comment]
Confirmed with a *different* Java.g4 :) working on it now...

**Comment by parrt** [comment]
Added:
```java
@Test
	public void testImportLargeGrammar() throws Exception {
		String slave = load("Java.g4", "UTF-8");
		String master =
			"grammar NewJava;\n" +
			"import Java;\n";

		System.out.println("dir "+tmpdir);
		mkdir(tmpdir);
		writeFile(tmpdir, "Java.g4", slave);
		String found = execParser("NewJava.g4", master, "NewJavaParser", "NewJavaLexer", "compilationUnit", "package Foo;", debug);
		assertEquals("", found);
		assertNull(stderrDuringParse);
	}
```

**Comment by EpsilonPrime** [comment]
Compiled the head version -- it looks fixed now, thanks!
