### ISSUE TITLE
NullPointerException in bad recursion rule

### ISSUE THREAD

**Issue by marcpawl** [antlr/antlr4#822]
Error on my part lead to discovering an exception being thrown while generating the grammar.

$ cat error.g4 

```antlr
grammar Error;

a:
  a | b;

b: 'B';
```

$ cat build.xml

```xml
 <project name="error" default="generate">
  <target name="generate" >
                <java classname="org.antlr.v4.Tool" fork="false" failonerror="true">
                        <arg value="-o" />
                        <arg value="java" />
                        <arg value="-package" />
                        <arg value="com.example" />
                        <arg value="-visitor" />
                        <arg value="-Werror" />
                        <arg value="error.g4" />
                        <classpath>
                                <pathelement location="antlr-4.4-complete.jar"/>
                        </classpath>
                </java>
</target>
</project>
```

```
$ ant
build.xml:3: java.lang.NullPointerException
	at org.antlr.v4.tool.Rule.getAltLabels(Rule.java:217)
	at org.antlr.v4.tool.Rule.hasAltSpecificContexts(Rule.java:200)
	at org.antlr.v4.semantics.SymbolChecks.checkForLabelConflicts(SymbolChecks.java:157)
	at org.antlr.v4.semantics.SymbolChecks.process(SymbolChecks.java:105)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:107)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
	at org.antlr.v4.Tool.process(Tool.java:387)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:346)
	at org.antlr.v4.Tool.main(Tool.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:217)
	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:152)
	at org.apache.tools.ant.taskdefs.Java.run(Java.java:771)
	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:221)
	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 0 seconds
```

**Comment by KvanTTT** [comment]
The rule seems fine, it can recognize a sequence of any size of `B`. For instance: `BBBBBB`

It's unclear why ANTLR can't handle it.

**Comment by parrt** [comment]
This can only match a single B right?

```
a:
  a | b;

b: 'B';
```

**Comment by KvanTTT** [comment]
On the contrary: it should match sequence of B with size >= 2. It seems I've figured out how to fix it.

**Comment by ericvergnaud** [comment]
Interesting that we struggle to agree…

I think Terence is right, it can only match a single B

here’s my breakdown for input ‘BB’:

	- try match a alt -> fails
	- try match b alt -> succeeds 
				  -> go to b rule
				  -> match ‘B’
 				  -> exit b rule
				  -> exit a rule

I don’t see why the runtime would try to match additional input when it has a non repeating and non greedy alternative ?

**Comment by KvanTTT** [comment]
Hmm, in this case it should be another error. I guess it's `EPSILON_LR_FOLLOW` (`left recursive rule <arg> contains a left recursive alternative which can be followed by the empty string`). The same case we have in [testCheckForLeftRecursiveEmptyFollow](https://github.com/antlr/antlr4/blob/master/tool-testsuite/test/org/antlr/v4/test/tool/TestLeftRecursionToolIssues.java#L36-L48).

For now it throws non informative `NONCONFORMING_LR_RULE`.

**Comment by KvanTTT** [comment]
> here’s my breakdown for input ‘BB’:

But ANTLR 4 is quite smart because it rewrites left recursive rules. For instance, for the following sample:

```g4
a
    : a '+'
    | 'B'
    ;
```

Rewritten rule is:

```
a
    :   ( {} 'B'<tokenIndex=15> 
        )
        (
          {precpred(_ctx, 2)}?<p=2> '+'<tokenIndex=11>
        )*
    ;
```

The abovementioned case:

```g4
a
    :   ( {} 'B'<tokenIndex=13> 
        )
        (
          {precpred(_ctx, 2)}?<p=2> a
        )*
    ;
```

Will be rewritten as (if some errors are fixed):

```
a
    :   ( {} 'B'<tokenIndex=13> 
        )
        (
          {precpred(_ctx, 2)}?<p=2> a
        )*
    ;
```

And it matches a sequence of `B`, not the single `B`. But I've not checked more complicated samples.

**Comment by ericvergnaud** [comment]
But that’s a different use case, no ?
The one posing problem is a | b, not a ‘+’ | ‘B’

**Comment by KvanTTT** [comment]
Yes, a bit different because of non empty alternative after removing of recursion rule refs. It seems like the second rewriting is also a bit incorrect because of it contains recursive rule ref (`a`) (despite the fact that it works). It should be:

```
a
    :   ( {} 'B'<tokenIndex=13> 
        )
        (
          {precpred(_ctx, 2)}?<p=2> 'B'<tokenIndex=13>
        )*
    ;
```

I need more investigation. But on my opinion, from the user expectation the rule should parser a sequence of `B` instead of single `B` despite the fact that ANTLR is LL parser but not LR.

**Comment by parrt** [comment]
yeah, without recursion and without an explicit loop, there's no grammatical way to match more than one symbol here.

**Comment by parrt** [comment]
Interesting, I get:

```
error(169): /tmp/foo/src/t.g4:3:0: rule a is left recursive but doesn't conform to a pattern ANTLR can handle
```

Oh right! Because `a` has to have something after it or I don't know what to do.   interesting that I do not get an exception however. We must've introduced something in a recent version. I'm using the intellij plugin 1.6. Same with 1.7, which is ANTLR 4.9.1

**Comment by parrt** [comment]
wow. my grammar brain has been asleep for too long. I just realized why that grammar is not good. `a : a | b;` is equivalent to `a : a; a : b` in non-ANTLR notation.  clearly `a : a` is meaningless. Anyway, just thought I would add this for the record as my brain figure this out last night while sleeping :)

**Comment by KvanTTT** [comment]
Anyway, it should be another error, seems like `EPSILON_LR_FOLLOW` but not `NONCONFORMING_LR_RULE`.

**Comment by parrt** [comment]
yep. something like that. In an optimal world we might have a better error message but it's probably not worth me thinking about it given that it is definitely a nonconforming LR rule :)
