### ISSUE TITLE
NullPointerException in bad lexer rule

### ISSUE THREAD

**Issue by hneuendo** [antlr/antlr4#935]
After "quick replace" I got this lexer rule in my grammar:

```antlr
CHARACTER_LITERAL
	:	''' '''
	;	
```

```
This generates an NullPointerException which is really hard to find out in a large grammar.
Exception in thread "main" java.lang.NullPointerException
	at org.antlr.v4.automata.ParserATNFactory.elemList(ParserATNFactory.java:490)
	at org.antlr.v4.automata.ParserATNFactory.alt(ParserATNFactory.java:477)
	at org.antlr.v4.parse.ATNBuilder.alternative(ATNBuilder.java:556)
	at org.antlr.v4.parse.ATNBuilder.ruleBlock(ATNBuilder.java:290)
	at org.antlr.v4.automata.ParserATNFactory._createATN(ParserATNFactory.java:186)
	at org.antlr.v4.automata.LexerATNFactory.createATN(LexerATNFactory.java:134)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:405)
	at org.antlr.v4.Tool.process(Tool.java:376)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:343)
	at org.antlr.v4.CSharpTool.main(CSharpTool.java:59)
```

**Comment by SOberhoff** [comment]
I'm realizing that this is the same as #959 that I reported.
