### ISSUE TITLE
crash on adding an argument to a rule

### ISSUE THREAD

**Issue by davidcok** [antlr/antlr4#953]
On a fairly large grammar (combined lexer and parser), which worked fine, I added a parameter to a parser rule :
 term[boolean ispred] : ...
and added an argument to every place that the rule was invoked, e.g.  term[ispred] or term[true]

Now running anltr on the grammar causes a crash:

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.antlr.v4.parse.GrammarTreeVisitor.visit(GrammarTreeVisitor.java:207)
	at org.antlr.v4.parse.GrammarTreeVisitor.visitGrammar(GrammarTreeVisitor.java:201)
	at org.antlr.v4.semantics.SymbolCollector.process(SymbolCollector.java:76)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:103)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:397)
	at org.antlr.v4.Tool.process(Tool.java:384)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:343)
	at org.antlr.v4.Tool.main(Tool.java:190)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.antlr.v4.semantics.SymbolCollector.discoverOuterAlt(SymbolCollector.java:111)
	at org.antlr.v4.parse.GrammarTreeVisitor.outerAlternative(GrammarTreeVisitor.java:2285)
	at org.antlr.v4.parse.GrammarTreeVisitor.ruleBlock(GrammarTreeVisitor.java:2198)
	at org.antlr.v4.parse.GrammarTreeVisitor.rule(GrammarTreeVisitor.java:1664)
	at org.antlr.v4.parse.GrammarTreeVisitor.rules(GrammarTreeVisitor.java:1242)
	at org.antlr.v4.parse.GrammarTreeVisitor.grammarSpec(GrammarTreeVisitor.java:481)
	... 12 more
Exception in thread "main" java.lang.NullPointerException
	at org.antlr.v4.tool.Rule.getAltLabels(Rule.java:217)
	at org.antlr.v4.tool.Rule.hasAltSpecificContexts(Rule.java:200)
	at org.antlr.v4.semantics.SymbolChecks.checkForLabelConflicts(SymbolChecks.java:157)
	at org.antlr.v4.semantics.SymbolChecks.process(SymbolChecks.java:105)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:107)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:397)
	at org.antlr.v4.Tool.process(Tool.java:384)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:343)
	at org.antlr.v4.Tool.main(Tool.java:190)

I'm dead in the water now, so help would be appreciated.

**Comment by parrt** [comment]
is term left-recur? is this a dup of https://github.com/antlr/antlr4/issues/773 ?

**Comment by davidcok** [comment]
Yes - it is left recursive, so I see I can't do the natural implementation (though an error message instead of a crash would be nice). Your book (which I did buy) could be clearer on using parameters in general and on disallowing this use in particular.
Thanks for the quick reply.
- David

**Comment by parrt** [comment]
you will note that the soon to be released version that response to that issue now generates a proper error message.

what is it about the book that is unclear about parameters ( other than left recursive arguments)? I'd be happy to add to the next release.

**Comment by davidcok** [comment]
Thanks.
Please do not misunderstand: I've been happily using ANTLR, including previous versions, for years, to create parsers in Java. I've been testing ANTLR's limits lately trying to implement a poorly designed grammar (too many ambiguities - produced by someone else) while modifying the grammar as little as possible.

Regarding rule parameters and return values - I would have expected a full description as a section under "Parser Rules" in the Grammar Reference
Your example of getting rid of left-recursion would be better if it also showed the effect on tail recursive rules.
One of the harder issues with any parser generator technology, including ANTLR, is implementing the parser to generate good (from a user's point of view) error messages. I'd like to see a very full discussion of that in the book, with plenty of examples.
- David
