### ISSUE TITLE
Can't compile antlr4 on master

### ISSUE THREAD

**Issue by jason-wolfe** [antlr/antlr4#954]
Wanted to do a custom build since I need the fix for the javascript octal issue, which isn't in the RC yet.

```
➜  /tmp  git clone git@github.com:antlr/antlr4.git
Cloning into 'antlr4'...
remote: Counting objects: 59023, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 59023 (delta 0), reused 0 (delta 0), pack-reused 59021
Receiving objects: 100% (59023/59023), 30.82 MiB | 3.51 MiB/s, done.
Resolving deltas: 100% (31452/31452), done.
Checking connectivity... done.
➜  /tmp  cd antlr4 
➜  antlr4 git:(master) ./bild.py clean
bootstrapping; downloading bilder.py
target clean
bild succeeded
➜  antlr4 git:(master) ./bild.py compile
target compile
require parsers
build compile
require regen_tests
test generation complete
skipping compile
Traceback (most recent call last):
  File "/tmp/antlr4/bilder.py", line 847, in processargs
    target()
  File "./bild.py", line 88, in compile
    require(regen_tests)
  File "/tmp/antlr4/bilder.py", line 434, in require
    raise Exception()
Exception
bild failed
```

**Comment by jason-wolfe** [comment]
Based on the most recent commit I'm guessing that this is resolved by switching to mvn.

**Comment by jason-wolfe** [comment]
Running "mvn package" gave me /tmp/antlr4/runtime/Java/target/antlr4-runtime-4.5.1-SNAPSHOT.jar. Good to go, though the github wiki docs could use some updates.

**Comment by parrt** [comment]
yup. we'll get to that.
