### ISSUE TITLE
Small lexer grammar causes "Serialized ATN data element out of range."

### ISSUE THREAD

**Issue by WalkerCodeRanger** [antlr/antlr4#967]
Using ANTLR 4.5.1, I get the following exception:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element out of range.
    at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:370)
    at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:547)
    at org.antlr.v4.codegen.model.SerializedATN.<init>(SerializedATN.java:46)
    at org.antlr.v4.codegen.model.Recognizer.<init>(Recognizer.java:87)
    at org.antlr.v4.codegen.model.Lexer.<init>(Lexer.java:51)
    at org.antlr.v4.codegen.OutputModelController.lexer(OutputModelController.java:176)
    at org.antlr.v4.codegen.OutputModelController.buildLexerOutputModel(OutputModelController.java:129)
    at org.antlr.v4.codegen.CodeGenerator.generateLexer(CodeGenerator.java:142)
    at org.antlr.v4.codegen.CodeGenPipeline.process(CodeGenPipeline.java:73)
    at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:428)
    at org.antlr.v4.Tool.process(Tool.java:386)
    at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:345)
    at org.antlr.v4.Tool.main(Tool.java:192)
```

When trying to generate a lexer from this grammar:

```
lexer grammar Test;

Word : ~[ #]+;
Whitespace : [ ]+;
Enter : '#' -> mode(SKIP);

mode SKIP;
Skipped : ~[#]+;
Exit : '#' -> mode(DEFAULT_MODE);
```

Please note, that is the entire grammar, and I am trying to generate it directly not by importing it into another grammar.  The problem seems to be with including `-> mode(SKIP)`

**Comment by WalkerCodeRanger** [comment]
Ok, playing with it more.  The bug seems to be that you can't use a mode named "SKIP".

**Comment by KvanTTT** [comment]
It seems to me that mode can not have following names:
```HIDDEN, DEFAULT_TOKEN_CHANNEL, DEFAULT_MODE, SKIP, MORE, EOF, MAX_CHAR_VALUE, MIN_CHAR_VALUE```.
They bring exception during parser generation (in your case) or even worse unexpected behaviour during runtime (mode won't be activated).

This can be clarified from ```getConstantValue``` method in [LexerATNFactory.java](https://github.com/antlr/antlr4/blob/7d464aaca763151aa93857fb0db9b6f1129da055/tool/src/org/antlr/v4/automata/LexerATNFactory.java#L450).

I'am working on the same issue #996. And I'll fix your issue too.

**Comment by KvanTTT** [comment]
@parrt this issue should be closed a long time ago :)
